### ISSUE TITLE
API/ABI changes review for xxHash

### ISSUE THREAD

**Issue by lvc** [Cyan4973/xxHash#102]
The review of API/ABI changes for xxHash since 0.5.0 version: https://abi-laboratory.pro/tracker/timeline/xxhash/

Created with the help of open-source abi-tracker tool: https://github.com/lvc/abi-tracker.

The report is updated 3 times a week. Hope it will be helpful for users and maintainers of the library.

![xxhash-1](https://cloud.githubusercontent.com/assets/1517837/25326172/13adbc2c-28e0-11e7-8659-71c58bd4f78e.png)
![xxhash-2](https://cloud.githubusercontent.com/assets/1517837/25326178/1d4878b2-28e0-11e7-8694-870345c520fc.png)

## Environment
* Linux x86_64
* GCC 4.9
* xxHash 0.5.0 and higher

**Comment by Cyan4973** [comment]
This is a great tool @lvc , I really like it.

The compatibility warnings are related to changes in `XXH??_state_s` structure.

This structure should be used as an [opaque incomplete type](https://docs.oracle.com/cd/E19205-01/819-5265/bjals/index.html), that is, it must never be used directly.

The structure definitions are provided for situations where it's desirable to statically allocate state (typically on stack). Definition is [protected by a macro `XXH_STATIC_LINKING_ONLY`](https://github.com/Cyan4973/xxHash/blob/dev/xxhash.h#L244), which is disabled by default. As the name implies, it means it's not a good fit for dynamic linking, where ABI compatibility matters. It's less of an issue when source must be re-compiled.

ABI tracker seems unaware that these symbols are not accessible by default (since they are protected by a macro which must be explicitly stated).

Not sure if that's a feature which would be possible to consider for ABI tracker. I would like it much, since that's the way most of my projects are organized : an initial "stable" section, where API and ABI stability are paramount, and an "experimental" or "static" section, protected by a macro, where ABI and API can change.

**Comment by lvc** [comment]
XXH32_state_s and XXH64_state_s structures are now filtered from the analysis.

Thank you.
