### ISSUE TITLE
Whats the easiest way to show someone this hash is patents free ?

### ISSUE THREAD

**Issue by yassinm** [Cyan4973/xxHash#134]
Is there a link that would satisfy someone who wants to know if this hashing algorithm is patents free or no ? and yes i am not a lawyer but i felt i should ask just in case someone here has the answer. I can understand if no one has that answer.

**Comment by Cyan4973** [comment]
I would be _very_ surprised if there was any patent risk here.
Hashing is all pure math.
This is basically the unpatentable field by excellence.

**Comment by Cyan4973** [comment]
Math are labelled unpatentable even in US.

**Comment by Bulat-Ziganshin** [comment]
ANS is math too. It doesn't stopped patent trolls (nor Google).

**Comment by Cyan4973** [comment]
Well, due to the low bar of admission of patents, I wouldn't be surprised if someone successfully patented something on "2+2". But then, when trying to monetize through litigation, it's necessary to defend such patent in court, and that's where [it's a lot harder to justify](https://arstechnica.com/tech-policy/2011/08/appeals-court-says-only-complicated-math-is-patentable/).

Anyway, this is just a matter of where the current US legal system is. Any 2-lines of codes are subject to the same kind of "danger". There's no point in targeting a specific project about a general problem that's broadly applicable to everything.
