### ISSUE TITLE
About output format.

### ISSUE THREAD

**Issue by differentrain** [Cyan4973/xxHash#153]
Hi,
About the algorithm, I don't understand which result actually should be shown.
For example, if my system is little endian, and I got the hash, 0x1A2B3C in u32, if I want to convert this value to byte array,  shoud I need to reverse the array? Furthermore, if the result array required to be reverse, how to compare them?

**Comment by Cyan4973** [comment]
First, note that `XXH32()` result is an `unsigned`, and `XXH64()` result is an `unsigned long long`.
That means, these results are integral values, which is endian independent.
As long as you compare the values, endianess does not get in the way.

Same thing if you want to compare the representation of this value using hexadecimal notation : a number is a number, there is no 2 ways to represent it.

Now, if you want to compare the _layout_ of the value, as a succession of bytes in memory,
the recommandation is to use `XXHnn_canonicalFromHash()`, which will effectively write down the hash in memory using big endian notation, in order to match the layout of natural number when directly dumping memory in hexadecimal. The canonical format is always the same, whatever the endianess of the underlying platform.

**Comment by differentrain** [comment]
> First, note that `XXH32()` result is an `unsigned`, and `XXH64()` result is an `unsigned long long`.
> That means, these results are integral values, which is endian independent.
> As long as you compare the values, endianess does not get in the way.
> 
> Same thing if you want to compare the representation of this value using hexadecimal notation : a number is a number, there is no 2 ways to represent it.
> 
> Now, if you want to compare the _layout_ of the value, as a succession of bytes in memory,
> the recommandation is to use `XXHnn_canonicalFromHash()`, which will effectively write down the hash in memory using big endian notation, in order to match the layout of natural number when directly dumping memory in hexadecimal. The canonical format is always the same, whatever the endianess of the underlying platform.

gotcha, thank you for your replay！

**Comment by differentrain** [comment]
> First, note that `XXH32()` result is an `unsigned`, and `XXH64()` result is an `unsigned long long`.
> That means, these results are integral values, which is endian independent.
> As long as you compare the values, endianess does not get in the way.
> 
> Same thing if you want to compare the representation of this value using hexadecimal notation : a number is a number, there is no 2 ways to represent it.
> 
> Now, if you want to compare the _layout_ of the value, as a succession of bytes in memory,
> the recommandation is to use `XXHnn_canonicalFromHash()`, which will effectively write down the hash in memory using big endian notation, in order to match the layout of natural number when directly dumping memory in hexadecimal. The canonical format is always the same, whatever the endianess of the underlying platform.

gotcha, thank you for your replay！
