### ISSUE TITLE
Add std::hash, clhash, and google's farmhash to the benchmark suite

### ISSUE THREAD

**Issue by hungptit** [Cyan4973/xxHash#160]
Hi Yann,

My hash function benchmark results in Linux using Xeon CPU + gcc-5.5 have shown that xxHash is not significantly faster than std::hash (https://github.com/hungptit/clhash/blob/master/benchmark/string_short.svg) and is slower than both Google's farmhash + HybridHash (i.e modified version of clhash). Could you update your benchmark with these hash functions?

Regards,
Hung

**Comment by Cyan4973** [comment]
Thanks for these data points. It's a very thorough analysis.

The benchmark seems concentrated on small keys.
And, by the nature of the benchmark, I suspect the benchmark loops over keys of predictable length (always 1, then always 2, etc.)
For such scenario, I would suggest the use of `XXH_INLINE_ALL` compilation directive.
It's supposed to help, getting a bit closer to farmhash results (which are good).

Congratulation for your own great `clhash` algorithm by the way.

Note that the benchmark published on front page uses 32-bit binaries, 32-bit OS, and a pre-Haswell cpu. It also only benchmarks long keys (~100 KB), since xxHash was initially designed as a checksum replacement. I haven't published results on more modern platform, though 3rd party have. For example, I recommend reading Aras' excellent article at https://aras-p.info/blog/2016/08/09/More-Hash-Function-Tests/ , which takes the pain to test multiple target platforms.

To update benchmark results, I would need to update the test suite, and the test system itself.
But there is also an opened question regarding system-specific hashes.
They tend to work very well, but they also tend to be non-portable.
For example, there is the relatively recent meowHash, which relies on the presence of hardware AES instructions. Maybe you will want to have a look at it and include it in your comparison by the way.

I think these hashes are great and have a role, especially for self-consumed hashes. But for use cases where hashes are going to be stored and need to be read again many years later on any future kind of platform, it's a different story. This concern is especially important when there is no software backup path provided.

Therefore, it seems to be a different kind of category.
Maybe creating this category could be a way to still display some results regarding such hashes.

**Comment by lilianmoraru** [comment]
> BTW, I have created another benchmark for some popular hash functions and you can find detail information from this link https://github.com/hungptit/AquaHash/blob/master/benchmark.md. The benchmark results also show that the xxhsum command is significantly faster than other popular checksum commands i.e md5sum and sha1sum for medium and large files and I think it is one of the reasons why people tend to use xxHash in performance-critical applications.

Could you please also add the number of collisions? Cannot trust any hashing algorithm without this data.

**Comment by Cyan4973** [comment]
> Could you please also add the number of collisions? 

I'm starting something on the topic of collisions here :
https://github.com/Cyan4973/xxHash/issues/236#issuecomment-522051621

**Comment by hungptit** [comment]
@lilianmoraru I am trying to figuring out how to use @Cyan4973 code the measure the number of hash collisions. I will post the results later. BTW, beware that AquaHash is not portable like xxhash and it is only suitable for a limited number of applications.
