### ISSUE TITLE
Add my "clean C" implementation 

### ISSUE THREAD

**Issue by easyaspi314** [Cyan4973/xxHash#182]
This is about as clean and simple as it gets.

https://github.com/easyaspi314/xxhash-clean

Can it be added to either the main repo or as a link in the website?

**Comment by Cyan4973** [comment]
Looks great ! This can indeed be useful for reference

**Comment by easyaspi314** [comment]
I added the streaming implementations and also an example barebones xxhsum utility for an example.

It's all original code, and it only implements the checksumming files part.

**Comment by Cyan4973** [comment]
One possible idea would be to link your project from the `/doc` directory of `xxHash` (the one which contains the specification), under mention that it's a simplified readable version, that can be used to illustrate the spec.

**Comment by czMaxx** [comment]
I really like and support the initiative to stick with stdint.h in your project. Is there any obstacle that blocks its usage in the main xxh project? Some obscure platforms that we want to build it for? GCC 4+ (IIRC) and MSVC 2010+ should be perfectly compliant.

**Comment by easyaspi314** [comment]
stdint.h is a C99 and C++11 feature. We do use it in C++11 and C99 mode, and we just guess in C90 mode (tbh we should check limits.h)

I dunno, C developers have some obsession over strict C90 compliance for some weird reason. 

I was considering doing C99/C++11 in my reference implementation, but I decided against it because it turned out that the C90 compliance didn't really cause any issues.

A lot of those extra blocks could be omitted.

**Comment by czMaxx** [comment]
Well, since alphas, sparcs, itaniums and similar architectures are almost completely dead and we live in 2019, I'd suggest to move on and enforce C99 or C++ 11. Furthermore, it's almost impossible to satisfy all platforms and the optimization criteria can't be that broad. Nowadays, x86, x86_64 and ARMv7+ are the only suitable platforms. They are all little endian (ok, ARMs are bi-endian and can be somehow switched, but that's a very rare scenario) and alignment insensitive. Intel managed to remove the penalty for unaligned access in i5 and i7 and I believe that ARM did so as well. Breaking the limit of C90 would allow to write clearer code, which is accented when it comes to XXH3 where you want to take the advantage of MMX/SSE and just to comply with older standards you have to invent how to map it to shorter data types while not making the code messy. And, of course, using of newer compilers allows you to use intrinsics, which might be very helpful for perf tuning "to the bone".

**Comment by Cyan4973** [comment]
xxHash is designed for C90 compatibility, and must preserve this property.

I agree that C99 provides nice new features, but this is a discussion for a new code base.

**Comment by easyaspi314** [comment]
When writing library code, you have no clue who is going to use the code. 

I once got a complaint about how I used C99 code in one of my own libraries, and they wanted to use it but were limited by their project rules to use ANSI C only, [like many other people still do](https://github.com/search?q=-ansi&type=Code)

When writing desktop applications and stuff, sure, go ahead, use C99, use C11. 

Also, unaligned access isn't free on ARMv7, and big endian is still used a lot in the embedded world. A recent example was the Wii U.

**Comment by easyaspi314** [comment]
I do have to say that there is one thing I don't agree with in the normal code base:
```c
U64
U32
U16
BYTE
```
"One of these things is not like the other"

**Comment by czMaxx** [comment]
Ok, I see. Maybe I'm just lucky enough to work on projects that are built without these restrictions, because our customers have HW+SW combination that can handle it. You're right that my experience can't be generalized to other fields of the industry. Anyway, one must admit that using C90 almost 30 years later is somehow frustrating ;-)

**Comment by Cyan4973** [comment]
@easyaspi314's simple xxHash implementation is now mentioned and linked from the `/doc` directory.
