### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by tpetazzoni** [Cyan4973/xxHash#253]
The LICENSE file in the source code contains the text of the BSD 2-clause license. However, the file xxhsum.c has a header with indicates a GPLv2 license. Should the LICENSE file be clarified ?

**Comment by Cyan4973** [comment]
Indeed,
the _library_ is BSD-licensed, so that it can be easily integrated into any commercial product,
while the _CLI_ is GPL licensed, hence copyleft.
This difference is intentional.

The `LICENSE` document is applicable to the library, as stated in its first line.

I read your request as : add a second section to this document with the _CLI_ license .

**Comment by tpetazzoni** [comment]
Yes, clarifying that the CLI is under GPL + adding the GPL license text would indeed clarify things. Perhaps a clear statement that the library is under BSD-2c would be good because the simple "xxHash library" at the beginning of the LICENSE file is not completely clear that it means "The following license applies only to the xxHash library, not to its CLI".

**Comment by data-man** [comment]
It would be nice to relicense to MIT or Apache.
So xxHash can be ported to other MIT/Apache-languages.

**Comment by Cyan4973** [comment]
BSD is compatible with MIT.
