### ISSUE TITLE
Inconsistent return types

### ISSUE THREAD

**Issue by mgieseki** [Cyan4973/xxHash#28]
Hi,

xxhash.c defines a couple of unsigned types (`U16`, `U32`, etc.) depending on the implemented C standard. Since they are also used as return types of public functions, declaration and definition differ in some cases:

xxhash.h: `unsigned int  XXH32_digest (const XXH32_state_t* statePtr);`
xxhash.c: `U32 XXH32_digest (const XXH32_state_t* statePtr);`

`XXH32_digest` uses `unsigned long long`in both cases.

Wouldn't it be better to either use the U* types consistently in all declarations and definitions, or drop them altogether? 

Regards,
Martin

**Comment by Cyan4973** [comment]
For consistency, when it comes to prototypes defined into `.h`, yes it would be better to use the same spelling as the one in `.h`.

For the rest of the code, brevity is more important, because it improves readability, which is a critically important asset for a source code. So `U32` is to be preferred to `unsigned int`.

Using `U32` into `.h` seems also possible, but then you have the issue of namespace pollution : `U32` is too generic, and could be used somewhere in the user's code, possibly with a different meaning. So it must not be defined into `.h`. `XXH_U32` would be specific enough, but it would sacrifice brevity, which is the whole point of this typedef.

For `.c`, it's different : typedef definitions remain there, and do not pollute global namespace.

**Comment by mgieseki** [comment]
Yes, sure. But the definition of `uint64_t` for example depends on compiler and platform so that the different return types `U64` (defined as `uint64_t` for C99 compilers) and `unsigned long long` might be incompatible. In these cases, xxhash.c wouldn't compile successfully.
Maybe it's possible to use the uint*_t types everywhere and define them in xxhash.h for non-C99 and non-C++11 compilers. Not sure if that's also a too generic attempt, though.

**Comment by Cyan4973** [comment]
Latest update within "dev" branch (05f94bf2e0acdcbeb056d72ad2eb20f4f5d49e45)
make sure prototypes defined within `xxhash.h`
use exactly the same type spelling within `xxhash.c`.

That's all I plan to do for the time being.
I understand your question goes farther than that,
in particular, it underlines that `unsigned long long` may be mapped to something else than 64-bits.
That's true in theory. That being said, I've yet to receive a single report about it so far.

Since complexifying an interface shouldn't be treated lightly, I prefer to keep that kind of change for the benefit of a large enough user base. After all, corner case platforms can always fork the code to fit their needs.

**Comment by mgieseki** [comment]
OK, great. Thanks for adapting the types in the function signatures. I agree that the changes should indeed be sufficient for a wide range of target platforms.
