### ISSUE TITLE
Add ability to do checking of files to xxhsum cli.

### ISSUE THREAD

**Issue by 133794m3r** [Cyan4973/xxHash#29]
As it says above currently I'm using md5sum for my checking of files since it's the fastest algorithm out there currently that lets me do that. I would like it if xxhsum would be able to do  similar system, with a -c option and that would greatly speed up things for me. As at the moment I'm pretty sure all it does is hash the file but no way to check a file against a hash without using something else.

**Comment by Cyan4973** [comment]
I believe this request is equivalent to #21.
This is a legitimate request, I'm just lacking time and concentration to do it.

The request can be divided into 2 parts : 
 - make xxhsum compatible with wildcard characters, so that it can produce the hash of multiple files. This part can probably be done from inside xxhsum. It will likely be more efficient than repetitively calling xxhsum from an external script
 - `-c` check option : this one is a bit more complex to do. Nothing huge, just more complex.
Scripts from @beckermr can certainly help for such a task.
Sure, it offers a different user experience from `xxhsum -c`.
But that's still plenty useful while `-c` option is unavailable.

**Comment by Cyan4973** [comment]
Merged into #21

**Comment by 133794m3r** [comment]
I didn't realize that, I did a search on the issues it and it din't show up forme. I guess I'm kinda dumb sorry for creating a dup .

**Comment by Cyan4973** [comment]
don't be. It was just listed as PR instead of issue ;-)
