### ISSUE TITLE
Consider semantic versioning

### ISSUE THREAD

**Issue by leventov** [Cyan4973/xxHash#34]
Consider semantic versioning for xxHash. See http://semver.org/

I'm supporting an xxHash port to another programming language (Java), and ought to read all commits to determine whether I should put some fixes to the port, accordingly, or not. Neither version (r39, r40, ...), release messages (https://github.com/Cyan4973/xxHash/releases) nor commit messages point if hash algorithm was changed.

If you don't want to change versioning scheme, you could just put a short sentence in release messages, if this release has exactly the same semantics (improvements only), or has semantic changes.

**Comment by Cyan4973** [comment]
Hi Roman

xxHash uses rNN versioning scheme due to historical reason, dating back from the time the project was hosted on Google Code. Since Google code is dead, it makes less sense by now. 

xxHash 32-bits result has not changed since r3 (d6a6bd9e7289121c7bb858938d014508514efda6), hence since a long time ago.
64-bits has never changed since its introduction, by r35 (fb3a75cfa10e475c6dacc886da1d1435ef800065).
It is now considered a priority that each and every version of xxHash shall always generate the same hash result as previous versions. This property is checked in-built every time a benchmark is started (which also means, every time a modification is done).

So, while maintaining a port of xxHash into another language, you should never fear to generate, one day, some different result after an update on github : this scenario shall never happen.

API stability is a more complex issue. Latest change was r37 (d54caef13199c89c885c6fedc5f8e40206bf3cce), which was also the only time API was modified. So it has proven fairly stable too. 

What could happen too is the introduction of new, larger, hashes, such as 128 bits and more. I started working on that some time ago, but never found the time to finish it. Nonetheless, the item might come back in the future.

Which is to say : due to fairly good stability of upstream, MAJOR.MINOR.PATCH scheme doesn't bring any major benefit yet. But that's nonetheless possible to do it, if only to give a more "familiar" look. So yes, let's keep that item as an objective for a future release.

**Comment by leventov** [comment]
Thanks for the comprehensive overview.

Yes, in this case Major.Minor.Patch seems like overkill, but Major.Minor, where Minor is just the current "rN" version, and Major is 1, should look "safer" for port maintainers/newcomers.

Regarding the promise not to change hash outputs forever - this puts limitation on possible performance improvements, or fixes of the flaws if such found. [FarmHash](https://github.com/google/farmhash) takes an interesting approach - it is actually not a single hash function but a family of those, each in it's own namespace: `farmhashna`, `farmhashuo`, `farmhashte`, `farmhashxo`, etc. What changed from FarmHash 1.0 to 1.1 is just more functions (namespaces) were added, but the old were not altered.

**Comment by Cyan4973** [comment]
Adding new hash functions is indeed planned (see the paragraph above regarding 128-bits and beyond). But _current_ hash functions shall generate the same hash result in the future.

It's coherent with FarmHash's policy. The main difference being : there is no Namespace in C. So we can only add new functions.

**Comment by Cyan4973** [comment]
Latest update of the ["dev" branch](https://github.com/Cyan4973/xxHash/tree/dev) introduces semantic versioning.

Next release is planned to be labeled 0.5.0, using version numbers published into `xxhash.h`. It will also be displayed by `xxhsum`.

**Comment by Cyan4973** [comment]
merged into master

**Comment by leventov** [comment]
@Cyan4973 From the commit:

```
+#define XXH_VERSION_MAJOR    0    /* for breaking interface changes  */
 +#define XXH_VERSION_MINOR    5    /* for new (non-breaking) interface capabilities */
 +#define XXH_VERSION_RELEASE  0    /* for tweaks, bug-fixes, or development */
```

Am I understand right, that major version is not intended for breaking *algorithmic* changes? So, if you decide the algorithm has a flaw or could be improved, you will give the new hash function a different name, a-la FarmHash `na`/`uo`/etc. ?

**Comment by Cyan4973** [comment]
@leventov, yes, you are correct

**Comment by leventov** [comment]
Thank you for clarification
