### ISSUE TITLE
XXH3_64b seeded faster than unseeded?

### ISSUE THREAD

**Issue by baryluk** [Cyan4973/xxHash#374]
```
$ xxhsum -b -i10 -B16384
xxhsum 0.7.3 (64-bit x86_64 + SSE2 little endian), GCC 9.3.0, by Yann Collet
Sample of 16 KB...        
XXH3_64b                 :      16384 ->  1173174 it/s (18330.8 MB/s)  
XXH3_64b unaligned       :      16384 ->  1161654 it/s (18150.8 MB/s)  
XXH3_64b seeded          :      16384 ->  1193735 it/s (18652.1 MB/s)  
XXH3_64b seeded unaligne :      16384 ->  1179491 it/s (18429.6 MB/s)  
```

I have seen seeded as high as 19100MB/s, but unseeded is always less than 18700MB/s in my benchmarks. That seems weird.

CPU: AMD Ryzen Threadripper 2950X 16-Core Processor

It is not due to CPU frequency boost or thermal throttling, if it was the case the seeded would be actually lower, due to being later in the benchmark sequence.

Build logs: https://buildd.debian.org/status/fetch.php?pkg=xxhash&arch=amd64&ver=0.7.3-2&stamp=1586775877&raw=0

compiler flags: `cc -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security  -Wdate-time -D_FORTIFY_SOURCE=2  ...`

**Comment by easyaspi314** [comment]
That's not a big deal.

Clang 9.0.1 for aarch64 has a similar deal with XXH128, on my Pixel 2 XL (2.46 GHz Qualcomm Snapdragon 835), XXH128 unseeded gets 4943 MB/s, but seeded gets 5164 MB/s.

I would be worried if there was a massive difference, but we are talking under 5% difference.

**Comment by easyaspi314** [comment]
You might find for sizes < ~300 bytes, that the differences are more logical.

**Comment by baryluk** [comment]
If seeded looks slightly faster, why not remove non-seeded version from the source, and just call seeded one with constant seed? Or would make performance for very short data suffer?

**Comment by baryluk** [comment]
Indeed for small data overhead of an initalization of the state is easily visible:

```
$ xxhsum -b -i10 -B24
xxhsum 0.7.3 (64-bit x86_64 + SSE2 little endian), GCC 9.3.0, by Yann Collet
Sample of 24 bytes...        
XXH3_64b                 :         24 -> 325587279 it/s ( 7452.1 MB/s)  
XXH3_64b unaligned       :         24 -> 324690044 it/s ( 7431.6 MB/s)  
XXH3_64b seeded          :         24 -> 262659705 it/s ( 6011.8 MB/s)  
XXH3_64b seeded unaligne :         24 -> 262716846 it/s ( 6013.1 MB/s)  
```

```
$ xxhsum -b -i10 -B128
xxhsum 0.7.3 (64-bit x86_64 + SSE2 little endian), GCC 9.3.0, by Yann Collet
Sample of 128 bytes...        
XXH3_64b                 :        128 -> 149460066 it/s (18244.6 MB/s)  
XXH3_64b unaligned       :        128 -> 148493700 it/s (18126.7 MB/s)  
XXH3_64b seeded          :        128 -> 127089311 it/s (15513.8 MB/s)  
XXH3_64b seeded unaligne :        128 -> 126996692 it/s (15502.5 MB/s)  
```

```
xxhsum -b -i10 -B512
xxhsum 0.7.3 (64-bit x86_64 + SSE2 little endian), GCC 9.3.0, by Yann Collet
Sample of 512 bytes...   
XXH3_64b                 :        512 -> 29823086 it/s (14562.1 MB/s)  
XXH3_64b unaligned       :        512 -> 29542045 it/s (14424.8 MB/s)  
XXH3_64b seeded          :        512 -> 25639852 it/s (12519.5 MB/s)  
XXH3_64b seeded unaligne :        512 -> 25438902 it/s (12421.3 MB/s)  
```

Not sure why 512 is slower than 128 bytes, but never mind.

As of the big data difference, the difference is small indeed, but I guess the issue is with gcc and clang, is that they decide to using immediets for some values instead of putting some hot constant values in registers. This probably leads to more pressure in the instruction decoder, reduces slightly speculative execution performance and makes code slightly bigger (but probably by few dozen bytes, not important).

**Comment by easyaspi314** [comment]
> Not sure why 512 is slower than 128 bytes, but never mind.

XXH3 is a hybrid hash. For very short lengths <= 16 bytes, we use specialized single round functions, for 17-240 byte lengths, we use a Mum (64-bit→128-bit multiply, then fold) variant, and anything after that, we use the SIMD accelerated UMAC variant.

**Comment by Cyan4973** [comment]
> seeded faster than unseeded?

As you have already noticed, for long hashes, the core loop is identical between both seeded and unseeded variant, but the seeded variant has an additional initialization step.

Therefore, the seeded variant should be slower, even if it's only by a very little (initialization costs quickly become negligible). But sometimes, it does get faster nonetheless, due to badly controlled side effects.

A classical issue is instruction alignment. Note that this is different from _data_ alignment, which can be controlled. _Instruction_ alignment cannot be controlled from C. 
Depending on which exact address a hot loop begins, it results in better or worse performance, due to internal cpu details which are hard to explain and change with hardware generations, even more so between AMD and Intel. A code must be very well optimized to get into such a territory where these side effects are measurable. 
Compilers try to make an "educated guess", but since they don't know the exact architecture, they are stuck with some "approximate default". Even when they are informed of the architecture, they don't necessarily know all the details, as some of them are not documented, in order for the cpu manufacturer to be able to change them. Then, randomly, performance can swing depending on what _else_ is present in the binary around the hash function.

In order to be convinced by the randomness of the impact, just change the compiler, or even better the compiler version. And you'll notice that the ranking between the seeded and the unseeded variants change, using the same source code.

Anyway, the impact remains relatively limited for the reported case, so it's an intellectual curiosity, but it does not matter much.

**Comment by baryluk** [comment]
True. I have seen code alignment and ordering play a role in microbenchmarks (and of course exact behavior would differ on various CPU models, generations, as microarch is changing). I even expirienced changing unrelated and non-executed at runtime code, in a function that is never called or referenced from a code under test, and changing that function did change performance of the tested code. All because size of this unrelated function, made it just compiler and linker do slightly different decisions on collocating functions, or moving them a little in address space. I remember some tool based on clang to randomize code layout in binary so one can get more reliable information about these effects, and what really is happening.

I think it was this one, called Stabilizer - https://people.cs.umass.edu/~emery/pubs/stabilizer-asplos13.pdf , also with sources https://github.com/ccurtsinger/stabilizer , a bit old, but maybe there are newer versions somewhere.

Yes, you are right, this is not an issue, I just thought maybe there is bug, as initially it was weird to me, so I reported it.

**Comment by easyaspi314** [comment]
Instruction alignment is a good point: Clang (and possibly GCC, not sure) for x86 will always align branches with nops to fix an errata with some Intel -lake processors.

**Comment by Cyan4973** [comment]
I can confirm the impact of instruction alignment, notably visible in latest versions of the library, with the potential to impact performances by ~20% depending on how "lucky" the hot loop ends up being aligned, itself depending on what _other_ code lies around, how it's compiled, which version, etc.

I suspect that some careful assembly statements could help mitigate the issue, or at least reduce the random performance jump, by "force-pinning" the instruction alignment.
That's a full topic in itself.
