### ISSUE TITLE
Is the xxHash3 C reference version actually the fastest one? 

### ISSUE THREAD

**Issue by LifeIsStrange** [Cyan4973/xxHash#444]
I would have thought that C++20/rust features would allow some optimizations/compiler hints that cannot be reproduced in C and therefore allow for an even faster implementation!

**Comment by easyaspi314** [comment]
> I would have thought that C++20/rust features would allow some optimizations/compiler hints that cannot be reproduced in C

Aside from exceptions, everything that can be done in C++ and Rust can also be done in C, just with some boilerplate. 

As a matter of fact, Rust uses the same backend as Clang.

**Comment by Cyan4973** [comment]
> C++20/rust features would allow some optimizations/compiler hints that cannot be reproduced in C and therefore allow for an even faster implementation!

You are welcomed to try !

**Comment by felixhandte** [comment]
All programs written in compiled languages must eventually be translated into a binary executable, in machine instructions of the target architecture. So the question is whether some other program + language + compiler combination would be able to produce better instructions.

In that light, an important thing to note about this implementation is that much of it is not really C as it is normally thought of (i.e., a cross-platform language for writing portable programs): the performance-sensitive parts of the implementation are all written in multiple, architecture-specific versions which make very heavy use of compiler intrinsics, to more or less force the compiler to produce the desired sequence of instructions. E.g., see how the internal function `XXH3_accumulate_512()`, which in normal C can be written [this way](https://github.com/Cyan4973/xxHash/blob/cd59de7b583d8e8b0067805c36a93eeffc7c6f84/xxhash.h#L3502-L3518), has different implementations for specific instruction sets, [AMD64 SSE2](https://github.com/Cyan4973/xxHash/blob/cd59de7b583d8e8b0067805c36a93eeffc7c6f84/xxhash.h#L3244-L3277), [AMD64 AVX2](https://github.com/Cyan4973/xxHash/blob/cd59de7b583d8e8b0067805c36a93eeffc7c6f84/xxhash.h#L3138-L3170), [ARM NEON](https://github.com/Cyan4973/xxHash/blob/cd59de7b583d8e8b0067805c36a93eeffc7c6f84/xxhash.h#L3343-L3378), and [PPC VSX](https://github.com/Cyan4973/xxHash/blob/cd59de7b583d8e8b0067805c36a93eeffc7c6f84/xxhash.h#L3437-L3466).

I'm curious what features you think would help in the higher level languages you mentioned? Normally these are understood as (compared to C) providing abstractions and tools that make the language more expressive, rather than producing faster execution.
