### ISSUE TITLE
xxh3 for 32-bit hashes

### ISSUE THREAD

**Issue by 5e3** [Cyan4973/xxHash#453]
I guess it doesn't matter which bits I'm using or is it recommended to e.g. xor the higher 32bits with the lower 32bits?

**Comment by easyaspi314** [comment]
I would XOR fold the hash.

**Comment by Cyan4973** [comment]
In order to extract 32-bit from a _good_ 64-bit hash result,
there are many possible choices, which are all valid.
I would typically grab the lower 32-bit and call it a day.

Grabbing any other 32-bit (the upper part for example) is fine too.

xoring higher and lower bits makes more sense whenever the produced hash offers dubious quality.
FNV, for example, has poor mixing in its lower bits, so it's better to mix with the higher bits.

XXH3 already performs significant output mixing before returning the data,
so it's not beneficial to add another xorfold stage.
