### ISSUE TITLE
Improve documentation on how to actually provide an stdin for xxhash.exe utility.

### ISSUE THREAD

**Issue by frenchiveruti** [Cyan4973/xxHash#461]
Hello, I admit that I'm a complete ignorant on when it comes to how stdin works, but if I understood correctly this website:
https://www.digitalocean.com/community/tutorials/an-introduction-to-linux-i-o-redirection 
Using a command like:
`cat listoffiles.txt | ./xxhsum.exe`
should give the stdout from cat and "pipe" it into xxhsum, right?  
Well, I don't know what's going on but it simply does the checksum for the listoffiles.txt and doesn't even care about it's contents or the output from cat.  
What am I doing wrong?  
I'm using a WLS with debian on Win10, here's a picture:
![imagen](https://user-images.githubusercontent.com/1095997/95889119-8cd27380-0d71-11eb-986d-0a23c01e4b00.png)

A simple "how to make a text file and use it as stdin" in the wiki with some dumb example like this would really help.  
Thanks.

**Comment by Cyan4973** [comment]
The pipe command `cat FILE | xxhsum` is equivalent to `xxhsum FILE`,
which means it  hashes the _content_ of `FILE`.
It doesn't push the content of the file into the command line itself.

I guess you have already understood that by now,
since you also provided the answer to this problem [in this thread](https://github.com/Cyan4973/xxHash/issues/109#issuecomment-707912584) : 

```
for FILE in $(cat list.txt); do xxhsum $FILE >> hashes.txt; done
```

Similar construction can be performed with `xargs` too.

Wether this command should be part of a documentation is a good question.
This is more about knowing the shell command line than `xxhsum` itself,
so it's debatable.
But I see how it could help users in a similar situation.

**Comment by frenchiveruti** [comment]
Yeah my suggestion was more towards the xxHASH wiki here on github rather than for the "--help" command.
