### ISSUE TITLE
Compare with aHash

### ISSUE THREAD

**Issue by LifeIsStrange** [Cyan4973/xxHash#478]
https://github.com/tkaitchuck/aHash/blob/master/compare/readme.md

**Comment by Cyan4973** [comment]
A few comments : 

- The produced hash values are not stable, and btw the algorithm is properly branded as such. It means it's not possible to store or transmit the produced value to compare it later, as the result of the hash function will vary depending on exact version. It may even vary depending on local cpu characteristics. This is not a problem for the intended objective (in-memory hash maps).
- The core algorithm relies on hardware AES instructions, like a few other ones in the same category. It's unclear to me how portable the implementation is, though it sure works on modern Intel cpus.
- It's written in Rust. It's possible to import it into C/C++ projects, but it's not "trivial", and complexifies the build process. I also suspect that it can make a difference regarding inlining capabilities from/to each language, which can seriously impact performance comparisons, especially for small inputs.
- The reported speed of xxhash is off by almost an order of magnitude. I don't think the author is working hard to make its competitors fare as best as they can. So I would take these comparisons with a grain of salt.
- Since the algorithm is focused on speed and small data, a comparison with XXH3 is more appropriate

I did a serie of evaluations, and in these tests, ahash is fast, but not as much as reported in the table. On small data, ahash is competitive with xxh3 (same ballpark), which probably boils down to the fact that ahash uses similar access technique as xxh3 for small data. Then xxh3 is slowly building a lead as input size grows. On large data (specifically 1KB and beyond), I measure a ~+50% faster speed advantage for xxh3, and even larger when using `clang` with `avx2`.

In terms of collision ratio, the hash is reasonably good for long inputs, featuring a collision rate roughly 2x larger than it should be, thus equivalent to a 63-bit hash. While it's not perfect, it's still good enough and reasonably usable, notably better than many other AES-based hash algorithms. 
However, when it comes to small inputs, the situation is not good: I measure collision ratios > x100 than reference (corresponding to a loss of distribution of 7-8 bits) and sometimes much higher depending on exact scenario. This quality issue is small enough to remain undetected in smhasher tests, since it was designed for the 32-bit era and can't reliably detect collisions beyond 50-bit of distribution. But it's nonetheless too high to be considered in the acceptable range. 

So, all in all, it's a fast hash, with decent quality at large length, but a bit less satisfying on shorter lengths. I presume the author focused on a really fast algorithm for short lengths, and considered that as long as the hash would pass smhasher, it would be fine. Unfortunately, smhasher is a decent a baseline, but is far from capturing "everything", and can be gamed. It's up to each author to go beyond that baseline.
 
Finally, what really stands out is the first point : there is a big requirement difference between an algorithm that must remain stable across versions and hosts, and another one which can ignore this requirement because it's limited to in-session usages. They simply don't address the same range of scenarios.
