### ISSUE TITLE
Warning about stringop-overflow on 32-bit Windows

### ISSUE THREAD

**Issue by DavisVaughan** [Cyan4973/xxHash#482]
When compiling a project that includes xxhash on 32-bit Windows, using the mingw-w64 gcc toolchain (version 8.3.0), I get the following warning:

```c
In file included from internal/hash.c:4,
                 from internal.c:12:
In function 'XXH_memcpy',
    inlined from 'XXH3_update' at internal/xxhash/xxhash.h:4089:13,
    inlined from 'hash_bytes' at internal/xxhash/xxhash.h:4674:12,
    inlined from 'hash_char' at internal/hash.c:156:3:
internal/xxhash/xxhash.h:916:12: warning: 'memcpy' reading 258 or more bytes from a region of size 4 [-Wstringop-overflow=]
     return memcpy(dest,src,size);
            ^~~~~~~~~~~~~~~~~~~~~
```

I am defining `XXH_INLINE_ALL`, but nothing else. I am trying to use XXH3.

It _seems_ like, according to this post, that XXH3 should work for 32-bit Windows http://fastcompression.blogspot.com/2019/03/presenting-xxh3.html#bit-friendliness

FWIW my goal is to include xxhash into an R package, and this is the toolchain that Windows users get when compiling R packages. The relevant PR where I first noticed this problem is: https://github.com/r-lib/rlang/pull/1058/files, and the error occurred on this Github actions build https://github.com/r-lib/rlang/runs/1454252917?check_suite_focus=true#step:10:73. The error there isn't super informative, but I downloaded the entire log and found the warning that I copied in above in the 32 bit windows section. The 64 bit windows build works fine.

**Comment by DavisVaughan** [comment]
It seems like the 32-bit windows build on appveyor that uses mingw uses gcc 5.3.0, and that doesn't throw the warning. I can confirm that a Windows build of R that had a version of gcc that was earlier than 8.3.0 also didn't throw the warning. So maybe that is why this hasn't been noticed before? The check that throws this warning was probably added in a newer version of mingw's gcc than what you are testing with.

https://ci.appveyor.com/project/YannCollet/xxhash/builds/36560579/job/p7fxt7hhx18m4630#L29

Appveyor notes on mingw 32-bit version:
https://www.appveyor.com/docs/windows-images-software/#mingw-msys-cygwin

Update: Indeed this warning did not exist in gcc 5.3.0. It seems like maybe it was added around gcc 7, based on the dates here?
https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=ee92e7bafb52d267f52e4c48edada5f279bcf591

**Comment by Cyan4973** [comment]
Traces are strange.
The line were the issue happens is : `XXH_memcpy(state->buffer + state->bufferedSize, input, len);`
and the message is `reading 258 or more bytes from a region of size 4`.
This suggest that `len==258` while `input` points to a region of size 4.
Both variables are under direct control of the caller, as they reach this line without any modification.
So this would suggest an error on the calling  side.

That being said, to make matter mode complex, the previous line  `if (state->bufferedSize + len <= XXH3_INTERNALBUFFER_SIZE) {` should guarantee that, if `len==258`, the `memcpy` line will never be reached since the test will necessarily be false, as `XXH3_INTERNALBUFFER_SIZE == 256`. Since it is a runtime test, it's unclear how a compiler could use a fast static analysis to guarantee that this branch will be taken, hence make the warning relevant.

Since traces aren't helpful enough, for more investigation, it is important to be able to reproduce the issue.
What is called "32-bit  Windows" ?
Do you mean generation of a 32-bit binary using mingw32, or mingw-w64 in 32-bit mode, irrespective of the OS itself which can nonetheless be 64-bit ?
Does it happen while compiling xxHash in 32-bit within any program, or only specifically with this R binding ?
Is the issue still present when _NOT_ using `XXH_INLINE_ALL` ?
Does the generated binary work or segfault ?

**Comment by DavisVaughan** [comment]
> Do you mean generation of a 32-bit binary using mingw32, or mingw-w64 in 32-bit mode, irrespective of the OS itself which can nonetheless be 64-bit ?

While the issue originally happened in CI, I can also reproduce it locally on a Microsoft Surface with a 64-bit OS running Windows 10 Pro version 2004. When using R on a Windows machine, it uses mingw32 to generate a 32-bit binary.

> Does it happen while compiling xxHash in 32-bit within any program, or only specifically with this R binding ?

Sorry, I'm not quite competent enough to get a C program compiled and working on Windows when not doing it through R :/, but my best guess is that it would happen outside of R too.

> Is the issue still present when NOT using `XXH_INLINE_ALL` ? 

I just tried replacing it with:

```
#define XXH_STATIC_LINKING_ONLY
#define XXH_IMPLEMENTATION 
```

and the warning does indeed go away.

> Does the generated binary work or segfault ?

There are a few simple hash generation tests that I have been running at the R level across all of my builds. Even with the warning, these tests pass without any issues. So the hashes generated when compiled with mingw32 still seem to be correct.

**Comment by easyaspi314** [comment]
Perhaps try removing the implementation-defined behavior that may be throwing off the static analysis?

Static analysis typically doesn't work right when you do weird things like reading part of an object.
```c
static inline
void hash_char(R_outpstream_t stream, int input) {
  static int n = 1;
  void* p_input = (void*) (&input); // <-- implementation defined behavior!
  hash_bytes(stream, p_input, n);
}
```
This code not only reads only part of a basic object (violating the strict aliasing rule), but it also would effectively read `input >> 24` on a big endian system.

On little endian, it would work as if we give it `0x04030201` as an input, it would be layed out as so:
```
p_input[0, 1, 2, 3]
        01 02 03 04
```
but on a big endian system, it would be the reverse:
```
p_input[0, 1, 2, 3]
        04 03 02 01
```
It would read 0x04, not 0x01, so it would read the wrong thing. This makes a rather sneaky bug if someone compiles for, say, s390x or PPC.

To eliminate this possibility, try this:
```c
void hash_char(R_outpstream_t stream, int input) {
  static int n = 1;
  unsigned char byte = (unsigned char) input;
  unsigned char* p_byte = &byte;
  hash_bytes(stream, p_byte, n);
}
```
I also removed the redundant `void*` cast: C and C++ allow all pointers to be converted to `void*`.

A general rule of thumb is that you should rarely ever need to cast a pointer in C. The only times it is generally acceptable are when you are casting from `void*` in a generic function (e.g. `qsort` comparators), converting to a `char*` pointer, or trying to write C++ compatible code where you need to cast `void*` pointers from `malloc`.

**Comment by DavisVaughan** [comment]
@easyaspi314 thank you for taking a look! That is indeed a bug on my part. I'll fix this and update to your suggestion, which does seem to be what I really wanted.

That said, I've changed to your suggestion on my Windows machine and still see the warning - except it says `region of size 1` rather than `region of size 4`, which makes sense, I think, since we changed from an int* to an unsigned char*

**Comment by easyaspi314** [comment]
Hmmmm, so the strict aliasing violation did have *some* effect, as GCC now correctly assumes it is copying one byte. Interesting. 

Some other observations:
> `using platform: x86_64-w64-mingw32 (64-bit)`

This is actually 64-bit, not 32-bit, it is just using the mingw32 toolchain. mingw32 can be 64-bit, just like how mingw64 can be 64-bit. Yes, it is confusing.

> The line were the issue happens is : XXH_memcpy(state->buffer + state->bufferedSize, input, len);
and the message is reading 258 or more bytes from a region of size 4.
> This suggest that len==258 while input points to a region of size 4.

@Cyan4973, the trace points to [the second `memcpy`](https://github.com/r-lib/rlang/blob/969a1632998df15be4ddb2c0aec55d0c49d1a965/src/internal/xxhash/xxhash.h#L4089).

As for what I think is happening, the overflow seems to be GCC assuming `state->bufferedSize` is somehow *negative* (specifically `(uint32_t)-2` or `0xFFFFFFFE`). 

If `state->bufferedSize` is assumed to be `0xFFFFFFFE`, adding `1` would be `0xFFFFFFFF`, which *is* larger than `XXH3_INTERNALBUFFER_SIZE`, so that first branch would not be taken. I just don't understand why GCC would come to that conclusion.

What happens if you use `size_t` instead of `int` for the update sizes in `hash_bytes()`? I don't see how that would make a difference, but it is good practice nonetheless to avoid mixing signed and unsigned types. I just want to get rid of as many variables as possible. 

If THAT doesn't fix things, perhaps try adding this in `XXH3_update()`? 
```c
        /*
         * Internal buffer is partially filled (always, except at beginning)
         * Complete it, then consume it.
         */
        if (state->bufferedSize) {
            size_t const loadSize = XXH3_INTERNALBUFFER_SIZE - state->bufferedSize;
            if (loadSize > XXH3_INTERNALBUFFER_SIZE) {
                 /* Integer underflow. Should never happen unless the state was modified externally. */
                 return XXH_ERROR;
            }
            XXH_memcpy(state->buffer + state->bufferedSize, input, loadSize);
```
That might actually be a decent idea to put in the update code to be extra safe. That is a very cheap branch — the compiler can just check the borrow flag from the subtraction. 

I might have to do some testing for myself later tonight when I am at my PC, as I am running out of ideas. 乁( •_• )ㄏ

**Comment by Cyan4973** [comment]
Indeed, if `bufferedSize == (size_t)(-2)`, then it explains the behavior.
The question is, how could it be set to such value ?
This code only updates `bufferedSize` at very few selected places, and it seems in control.

Was the `XXH3_state_t` state properly initialized before invoking `XXH3_128bits_update()` ?
I don't see it happening within either `hash_char()` or `hash_bytes()` ...

**Comment by Cyan4973** [comment]
In latest `dev` branch update, I've added an `assert()` to control that `bufferedSize` remains within bounds as expected.
If not, the `assert()` will fire up, execution will stop and program will exit with an error message on console.
This could notably happen if `XXH3_state_t` is not initialized.

`assert()` are only active in debug mode, which can be enabled by setting `XXH_DEBUGLEVEL` to a value `>= 1` during compilation.

**Comment by easyaspi314** [comment]
> Was the `XXH3_state_t` state properly initialized before invoking `XXH3_128bits_update()` ?
I don't see it happening within either `hash_char()` or `hash_bytes()` .

Well this is a compile time warning, on an externally linked function containing a state pointer. GCC cannot determine anything about that, as that function can be called from anywhere with anything. And besides, GCC would complain about `-Wuninitialized` in that scenario.

So for anything to happen, it would have to be starting at `hash_char()` and ending at `XXH3_update()`, and it has nothing to do with what `hash_char()` is called with.

Maybe we are overthinking a good old-fashioned compiler bug. Because I see no other way for this to happen. 🤔

Either that, or GCC simply knows too much and must be `sudo rm -rf`'d.

**Comment by DavisVaughan** [comment]
I tried swapping `int` for `size_t`. That did not work, same warning.

However, I tried adding the suggested:

```c
        /*
         * Internal buffer is partially filled (always, except at beginning)
         * Complete it, then consume it.
         */
        if (state->bufferedSize) {
            size_t const loadSize = XXH3_INTERNALBUFFER_SIZE - state->bufferedSize;
            if (loadSize > XXH3_INTERNALBUFFER_SIZE) {
                 /* Integer underflow. Should never happen unless the state was modified externally. */
                 return XXH_ERROR;
            }
            XXH_memcpy(state->buffer + state->bufferedSize, input, loadSize);
```

and that _does_ make the warning disappear!

As some proof, here is a separate PR I branched from my rlang one. I've added the suggestion to `xxhash.h` and the github actions `windows-latest (release)` build that previously threw the warning is now passing!
https://github.com/DavisVaughan/rlang/pull/1
