### ISSUE TITLE
Prefetch distance

### ISSUE THREAD

**Issue by easyaspi314** [Cyan4973/xxHash#485]
I was doing some testing about the prefetch.

On my Pixel, I was noticing that *short* prefetches do slightly better in NEON mode. Specifically, 64-128 bytes seems to be the best. However, the differences aren't huge. Anything larger than 320 is definitely NG. 

Additionally, in 32-bit ARM scalar mode (ARMv6T2), prefetching is definitely *detrimental*: `-DXXH_NO_PREFETCH` is about 8% faster (2265 MB/s vs 2017 MB/s).

Lastly, we should be using 0 on `__builtin_prefetch`'s locality; we only read the data once. 3 locality forces a temporal cache when we want the opposite.

**Comment by Cyan4973** [comment]
> we should be using 0 on __builtin_prefetch's locality; we only read the data once. 3 locality forces a temporal cache

Interesting. I've been testing this hypothesis.
It's tricky, as documentation is not plentiful, and definitions are left intentionally vague, to give implementers some room for execution.

Temporality `3` (max) has been selected because it instructs data to go to `L1` cache, and since we are _certain_ that we will need this data very soon, this access and cache occupation is not wasted : it will be needed anyway.

`gcc` documentation states : 
> A value of zero means that the data has no temporal locality, so it need not be left in the cache after the access.

So it looks pretty clear, and in line with your assertion.
Now, how is this compiler-level instruction _actually_ implemented in the cpus ?
Well, that's where it becomes messy.

Different architectures result in different capabilities, hence different translations. And they are not 1:1 equivalent.

When it comes to `x64`, our most important target, a `__builtin_prefecth(ptr, 0, 0)` is translated into a `PREFETCHNTA` instruction.
What does this instruction do ?
According to [Felix Cloutier](https://www.felixcloutier.com/x86/prefetchh) : 
> NTA (non-temporal data with respect to all cache levels)—prefetch data into non-temporal cache structure and into a location close to the processor, minimizing cache pollution.

What does that exactly means ? Well, it's now architecture dependent. Depending on the exact cpu model, the actual mechanism behind this instruction can be different. In all cases though, the main idea remains : it attempts to minimize cache pollution, through more or less successful mechanisms. For example, in some cases, it might reduce associativity to a single slot.
For more details and concrete examples, see [this interesting SO post](https://stackoverflow.com/a/53271365/646947).

At the end of the day, I presume benchmark should be our judge. Which gives : 

| Config | Compiler | locality = 3 | locality = 0 | diff |
| --- | --- | ---:| ---:| ---:|
| AVX2 | `clang` | 55 GB/s | 37 GB/s | -33% |
| AVX2 | `gcc` | 38 GB/s | 33 GB/s | -13% |
| SSE2 | `clang` | 28 GB/s | 26 GB/s | -7% |
| SSE2 | `gcc` | 28 GB/s | 25 GB/s | -11% |

So, all in all, the performance seems clear : using a micro-benchmark, locality `3` offers superior performance.

This would seem to end it.

However, there are 2 remaining topics of interest, and they are more difficult to check : 
- In some different architectures, the result could be different
- Perhaps more importantly, in more complex programs, where multiple parts of the code need the cpu cache, being a "good citizen" using less cache can result in a better overall performance, as more cache is left to other parts of the code, allowing then to run faster.

As can be guessed, this second effect interests me much. However, it's by definition extremely difficult to measure, being tied to each specific implementation.

I'll be happy to trade a performance advantage in micro-benchmarks vs a performance advantage in real-world application.
However, so far, we have no concrete proof that it would work.
It _seems_ it could help, but that wouldn't be the first time that an apparently good idea is contradicted by the facts.

So I'll wait for field reports, and if possible reproducible tests, before deciding to move the temporality argument from `3` to `0`.

**Comment by Cyan4973** [comment]
> On my Pixel, I was noticing that short prefetches do slightly better in NEON mode.
> (...)
> Additionally, in 32-bit ARM scalar mode (ARMv6T2), prefetching is definitely detrimental:

Note : the exact prefetch distance can be set at compile time, using `XXH_PREFETCH_DIST`, or even disabled altogether, with `XXH_NO_PREFETCH`.
=> https://github.com/Cyan4973/xxHash#build-modifiers

So there is some user control allowed on these topics.

Not sure if this is enough though, nor how it could be improved.

**Comment by Cyan4973** [comment]
I made another test with `__builtin_prefetch()` associated with a locality of `0`,
and with the default 100 KB test, it leads to a massive performance reduction,
so much that it's actually preferable to _not_ prefetch anything (28 GB/s => 20 GB/s).

This is likely because in such scenario, the 100 KB data effectively fits into L2 cache,
and a locality of `0` is essentially worse.

If I increase the size of data to hash to 100 MB, to get beyond L3 cache,
now prefetching with locality `0` produces a little gain (12.3 GB/s => 13.0 GB/s), instead of a loss.
Of course, the current locality `3` still gets the most performance improvement (15 GB/s).

It shows that employing a locality `0` is a tricky proposition,
it's useful when one is certain (or almost certain) that data is in RAM and not in cache.
But if data is already in cache, it's a performance loss.
That makes it more difficult, or at least more situational, to employ (how to be sure that data is not already in cache?).

In presence of these new elements, I believe it's safer to not change the current locality level.
Of course, as you mention, there are cases / platforms where it might be preferable to _not_ prefetch, or to select a different prefetching distance. Thankfully, there are Build Macros for such specific controls. Maybe all it takes at this stage is to underline their existence in the documentation.
