### ISSUE TITLE
Potential v9 release?

### ISSUE THREAD

**Issue by tristan957** [Cyan4973/xxHash#536]
My project at work is headed toward a v2 release later this year and we are evaluating whether we should update our dependencies. It looks like it has been almost 2 years since the last formal release. If there haven't been any improvements performance-wise, then maybe it doesn't make any sense for us to upgrade if what we have works.

**Comment by Cyan4973** [comment]
The last release, [`v0.8.0`](https://github.com/Cyan4973/xxHash/releases/tag/v0.8.0), was actually less than one year ago.

This release is only critical if you plan to use `XXH3` or `XXH128`.
For `XXH64` and `XXH32`, the differences are minimal enough that it doesn't matter.

There will be an update sometimes this year, but there is no point waiting for it, since there is no formal date set, and there isn't any major change expected.

**Comment by tristan957** [comment]
Looks like I can't do math. Thanks!

**Comment by tristan957** [comment]
@Cyan4973 sorry for bugging you after closing the ticket. When you say "This release is only critical...", does that mean that v0.8 has the XXH3 improvements you were mentioning, or do those improvements exist only on the master branch?

**Comment by Cyan4973** [comment]
I mean that `XXH3` has an officially finalized output value starting `v0.8.0`, meaning `XXH3(object)` will always produce the same `value` for the same `object` starting `v0.8.0` and for any future version, which is a major requirement if you plan to store or transmit the hash value.
Future improvements may impact speed, or memory usage, or add new capabilities, but the output value will always remain the same.
