### ISSUE TITLE
Support for C strings of unknown length

### ISSUE THREAD

**Issue by michaeleisel** [Cyan4973/xxHash#593]
I have a case where I'm hashing many short C strings whose length I don't know upfront. I can do `XXH3_64bits(string, strlen(string))`, but there `strlen` takes up a decent amount of time. It'd be nice if xxHash could speed this up and eliminate the need for strlen by finding the 0 byte as it's going through.

**Comment by Cyan4973** [comment]
Unfortunately, this would merely transfer the load, rather than eliminating it.

**Comment by easyaspi314** [comment]
Null terminated strings are already a performance nightmare with plenty of solutions. Take the length once, store it somewhere (in a struct and before the string pointer are two common patterns), problem solved.

However, `strlen` is insanely optimized because it is relied on so much. Any homegrown length calculation on the fly will probably be slower than a properly tuned strlen.

**Comment by michaeleisel** [comment]
It seems like both strlen and xxHash have the same sort of loop, iterating over vectors (although strlen's can be assumed to be aligned, since it doesn't need to combine bytes in a deterministic way). But I wonder if, each time xxHash loads a vector, it could use a vector instruction to check for 0. On the other hand, this means we have to worry about going past the end of a page, so maybe you'd have a check to make sure you're well before the page end and then an unrolled loop before the next page end check. I'll admit, it does get a bit tricky.

**Comment by Cyan4973** [comment]
Yes, that's the issue.
Modifying the hot inner loops to deal with `\0` detection is no small detail, it will likely impact `xxhash` performance in non-trivial ways.

There is also the topic of security vulnerability which becomes concerning, as an attacker able to modify the content of a buffer might be able to remove the `\0` character, resulting in out-of-bound reads, which are undefined behavior.

These are considerations I would rather leave to a dedicated `string` library.

**Comment by gzm55** [comment]
> I have a case where I'm hashing many short C strings whose length I don't know upfront. I can do `XXH3_64bits(string, strlen(string))`, but there `strlen` takes up a decent amount of time. It'd be nice if xxHash could speed this up and eliminate the need for strlen by finding the 0 byte as it's going through.

Is this way a little faster: read a small chunk of data from `string`, check `\0` then feed the data into streaming api.

**Comment by easyaspi314** [comment]
> > I have a case where I'm hashing many short C strings whose length I don't know upfront. I can do `XXH3_64bits(string, strlen(string))`, but there `strlen` takes up a decent amount of time. It'd be nice if xxHash could speed this up and eliminate the need for strlen by finding the 0 byte as it's going through.
> 
> Is this way a little faster: read a small chunk of data from `string`, check `\0` then feed the data into streaming api.

I doubt it. If these are in fact short strings, half of the time it is going to be just wasted copying memory into a small buffer instead of reading directly. The streaming API has a lot of overhead.

Additionally, for XXH3, it would need to make two passes anyways (at least for the first 240 bytes) because it uses *entirely different codepaths* depending on the length.

So it isn't something like XXH64 where you could write it to be 32 bytes at a time.

Additionally, if you are in fact calling strlen *once* per string, immediately before calling XXH3, it should be pretty fast because the string would end up being hot in cache.

I don't think this *alone* is the bottleneck, nor would making a hybrid strlen/xxh3 fix it.

**Comment by michaeleisel** [comment]
I wonder if ARM's SVE instructions make this more viable, since they can deal with the page boundary issue

**Comment by hzhuang1** [comment]
> I wonder if ARM's SVE instructions make this more viable, since they can deal with the page boundary issue

You think strlen() costs too much time. If xxhash takes this job, it may cost more time. So it's not an optimization.
Yes, ARM SVE instruction may speed up strlen(). But the SVE optimization must have been in string library already. Why do we invent the wheel twice? Using strlen() is a simpler solution.

**Comment by michaeleisel** [comment]
I agree that using strlen() is the simpler solution, and my question is whether the complexity of computing the length ourselves is worth it. Prior to SVE, strlen couldn't load chunks in the same way as xxHash, the chunks had to be aligned. This meant that merging strlen and xxHash would be significantly more complex. But now, it seems that we process the exact same chunks for xxHash as we would for strlen, meaning that when we process each new chunk, we can add a check at the start to find a 0 byte. This does not seem _that_ much more complicated, and the clear performance win (in principle) is that we only process each chunk once rather than twice. This means fewer instructions executed, and less memory loaded. I can imagine the latter is especially important for larger strings where the start of the string may have been moved out of the faster CPU caches. But, it's also true that @easyaspi314 's point still applies, that without knowing the length ahead of time, suboptimal code paths may be taken. So this API would need some sort of hint of what length range the string is probably in, and for the strings to have a predictable length range, and that may outweigh the possibility of perf wins.

**Comment by michaeleisel** [comment]
Looking at the benchmarks, I see that XXH3 and XXH128 are both measured as going faster than a RAM sequential read (although I'm not sure how that's possible). But if true, then it sounds then like it's strictly bottlenecked by memory bandwidth? Then I would think one could double their performance for large strings by doing this.

**Comment by easyaspi314** [comment]
> Going faster than a RAM sequential read (although I'm not sure how that's possible)

That can be possible in the following ways AFAIK:
 A. Wider bandwidth
 B. Cache
 C. Branching - XXH3 doesn't have to wait for branches as much because of A.

If XXH3 adds the strlen calculation, it misses out on C and potentially A. Meanwhile, depending on the strlen implementation, calling strlen immediately beforehand will warm up the cache (Most strings are small enough to completely fit in L2/L3 cache).

This would also add a lot of complexity and only slightly benefit SVE.
