### ISSUE TITLE
comparison with PJW

### ISSUE THREAD

**Issue by fabiocannizzo** [Cyan4973/xxHash#64]
It would be interesting to compare the performance of this function with PJW or ELF:
https://en.wikipedia.org/wiki/PJW_hash_function

Some source code is available at:
http://www.partow.net/downloads/GeneralHashFunctions_-_C.zip

**Comment by Cyan4973** [comment]
Hi @fabiocannizzo 

The described principles of [PJW](https://en.wikipedia.org/wiki/PJW_hash_function) should make it much slower than modern hashes.
Reason is, a PJW round is a single byte, while an xxHash round is 4 words (with words being 4 or 8 bytes depending on version). On modern CPU, it should make a large difference.

If you want to be sure, I can only invite you to integrate it into the excellent @aappleby's [SMHasher](https://github.com/aappleby/smhasher), which will test not only its speed but also the quality of this hash. It's not completely straightforward, but it shouldn't be too difficult either.

**Comment by fabiocannizzo** [comment]
Hi Yann.

Thanks for your speedy reply.

In am profiling part of my application and the current bottleneck is the hashing algorithm. My default implementation is pjw, where I introduced some loop unrolling (steps of 4). I work with strings of length between 1 and 25 characters. 

I tried to replace pjw with murmur3 or xxhash, and according to the profile the total execution time got a it slower, meaning either a lower throughput or more collision in downstream calculations. I have not investigated which one of the two.

Anyway, thanks for the suggestion.

Regards,
Fabio

**Comment by Cyan4973** [comment]
It's a good point.
Very small keys is an area were older hashes can still compete, because they are lighter. Though they also tend to have worse distribution properties unfortunately.

For example, xxHash has a special "finishing" mode for < 32 bytes, so it's the one used in your use case. That's a situation where xxHash cannot really flex its muscles, because its main loop is skipped.

That being said, it was tested with short keys, and found to be competitive with murmurhash in this area (same or lower nb of cycles per hash).

The SMHasher test advise still holds : Smhasher tests start with a speed benchmark, where the first part is dedicated to small keys. Here, you'll get a detailed nb of cycles per key length. It's likely to help you see which algorithm fares better on short keys. The rest of the tests will help you see which algorithm has better distribution properties.

Last minor hint : if your application is compiled in 32-bits mode, you'll be better off using `XXH32`, especially for short keys.

**Comment by fabiocannizzo** [comment]
Thanks for your advice.

Regards,
Fabio
