### ISSUE TITLE
vcpkg installation

### ISSUE THREAD

**Issue by hros** [Cyan4973/xxHash#641]
I am trying to use vcpkg for installation
The procedure in the readme results in header files and static libraries (*.a) in the installed sub directory

How can I create a shared library using vcpkg?

additionally, how can I specify a version to build using vcpkg (in case I would like to build an older version)

**Comment by t-mat** [comment]
Hi @hros,

> How can I create a shared library using vcpkg?

If you're using `vcpkg` on Windows, you can do it with "triplets".

```
# DLL
vcpkg install xxhash:x64-windows

# Static
vcpkg install xxhash:x64-windows-static
```

But for POSIX flavored platforms, `vcpkg` doesn't support "triplets" for shared library.
You need to write your own script for it.  Please refer their document : [Overlay triplets example - Building dynamic libraries on Linux](https://vcpkg.io/en/docs/examples/overlay-triplets-linux-dynamic.html) and [their discussion](https://github.com/microsoft/vcpkg/discussions/19127).

> how can I specify a version to build using vcpkg

The following documents and threads may help you.

- [Take control of your vcpkg dependencies with versioning support - C++ Team Blog](https://devblogs.microsoft.com/cppblog/take-control-of-your-vcpkg-dependencies-with-versioning-support/)
- [microsoft/vcpkg/versioning.md](https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md)
- [How to specify a version of a library](https://github.com/Microsoft/vcpkg/issues/1681)

Please understand that you are asking about `vcpkg`.  Since here is an issue thread for `xxhash`, we can't provide complete answer of your question.
For further details, please ask `vcpkg` team directly.
