### ISSUE TITLE
xxhash.h->XXH_STATIC_ASSERT: potential build failure due to missing static_assert macro

### ISSUE THREAD

**Issue by aeolio** [Cyan4973/xxHash#664]
I just reported this to lighttpd; they directed me to this project. 

Cross-compiling with a uClibc toolchain results in a build failure, because uClibc does not define the static_assert macro. 
Including the macro definition in case it is not defined by <assert.h> fixes this issue

```
/* note: use after variable declarations */
#ifndef XXH_STATIC_ASSERT
#  if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L)    /* C11 */
#    include <assert.h>

/* uClibc does not define static_assert, but provides _Static_assert */
#    ifndef static_assert
#      define static_assert _Static_assert
#    endif

#    define XXH_STATIC_ASSERT_WITH_MESSAGE(c,m) do { static_assert((c),m); } while(0)
#  elif defined(__cplusplus) && (__cplusplus >= 201103L)            /* C++11 */
#    define XXH_STATIC_ASSERT_WITH_MESSAGE(c,m) do { static_assert((c),m); } while(0)
#  else
#    define XXH_STATIC_ASSERT_WITH_MESSAGE(c,m) do { struct xxh_sa { char x[(c) ? 1 : -1]; }; } while(0)
#  endif
#  define XXH_STATIC_ASSERT(c) XXH_STATIC_ASSERT_WITH_MESSAGE((c),#c)
#endif

```

**Comment by t-mat** [comment]
Hi @aeolio,

I'm really sorry.  But I believe we should not support uClibc with C11 or later C standard compilers.  Because

(1) uClibc's `<assert.h>` is not compatible with C11.  Their comment claims that it's compatible with C99.  https://git.uclibc.org/uClibc/tree/include/assert.h#n19
(2) Therefore, you should not use uClibc's `<assert.h>` with C11 or later C standard compilers.
(3) If you want to use uClibc with modern C compiler, you must indicate C standard version explicitly.  e.g. `-std=c99`

Also,

(4) If you really want to use `xxhash.h` with uClibc and C11 or later compiler, you must define `XXH_STATIC_ASSERT(x)` externally with compiler option, etc.
(5) If we need to implement something special for uClibc, we must check their special macro `__UCLIBC__`.  https://git.uclibc.org/uClibc/tree/README#n68

**Comment by easyaspi314** [comment]
I ran into a similar issue when messing with an old version of the NDK. (Side note: 310/130/190 MB/s on an actual 600MHz ARM1136)

We should use `_Static_assert` on C11.

**Comment by aeolio** [comment]
Hi Takayuki, 

Using `_Static_assert` would definitely help - it is supported by the compiler, and not dependent on the library implementation. As to the missing macro, I understand that I should rather follow this up with the library project (this is `uclibc-ng` - I always forget that this is a separate project, not an evolution). 

Kind regards, Andreas
