### ISSUE TITLE
Remove opaque states

### ISSUE THREAD

**Issue by iboB** [Cyan4973/xxHash#704]
Why are the `XXH*_state_t` structures opaque?

If they are moved to the public part of the library, there would be no need for `*_createState()` functions and the `XXH_NO_STDLIB` configuration, and the associated documentation. Moreover, there won't be a need for users to actually allocate them if they don't want to and using auto variables for them would be easy, even encouraged, and this (at least slightly) improves performance.

I think it's a good idea to make them non-opaque. Only document that they should be treated as opaque and one should never actually touch any of their fields. 

I think I can create a PR for this if there's interest

**Comment by t-mat** [comment]
Hi @iboB,

> Why are the XXH*_state_t structures opaque?

The following issues and answers may help you to understand our decision.

- https://github.com/Cyan4973/xxHash/issues/63
- https://github.com/Cyan4973/xxHash/issues/75#issuecomment-231581396
- https://github.com/Cyan4973/xxHash/issues/102#issuecomment-296740423

**Comment by Cyan4973** [comment]
These structures are already public.
They are just guarded by a macro `XXH_STATIC_LINKING_ONLY`, to emphasize the fact that the author fully acknowledges that employing these structures can only be done in the context of static linking (alternatively, `XXH_INLINE_ALL` is equivalent for this topic).

In dynamic linking mode, using these structures directly carry a risk of version mismatch: if the content of the structure changes between the version installed on target's system and the header's version used to compile the binary, this would result in seriously nasty bugs.
Therefore users of the dynamic library are safer to stick with `*_createState()`.

**Comment by iboB** [comment]
Right. Thanks.

So this is to preserve ABI compatibility in case a shared library is used. When I see this I'm thinking when the library is used with `dlopen/LoadLibrary` and `dlsym/GetProcAddress`, but in such a case the header won't be available and the states will have to be opaque anyway (so `_createState` need to be preserved for this scenario).

But if the header *is* used how can the ABI compatibility suffer even if it is in a shared library scenario? Do you envision that software might be linked with `xxhash.so` and then shipped to a system with a different (older or newer) `xxhash.so`?

**Comment by easyaspi314** [comment]
ABI breakage is an issue that can cause many packages to be held back or cause mass updates.

That is, for example, why older Debian and Ubuntu releases ship with old GCC versions. While `glibc` has an incredibly stable ABI, `libstdc++`, GCC's C++ library, does not. You can't link to the wrong libstdc++, unless you want multiple copies of the library (which ruins the benefit of package managers).


However, a more extreme example of a problem with ABI breakage is when someone takes a binary compiled against one version of the system library and sends it to another machine with that same system library name, but a different version.

The issue is static allocation.

Let's say libpi.so v1.0 has a function called `get_pi()` which takes a pointer to `int`, and stores an arbitrary value in that value.
```c
void get_pi(int *pi)
{
    *pi = 314159265;
}
```
Your program links against this library.
```c
int random(void)
{
    int pi;
    get_pi(&pi);
    return pi;
}
```

In assembly (i386 fastcall), it would be like this. The compiler reserves 4 bytes on the stack for the `pi` variable, and passes that address to get_pi.
```asm
random:
    sub     esp, 4
    mov     ecx, esp
    call    get_pi
    mov     eax, [esp]
    add     esp, 4
    ret
```

But the libpi developers quickly realize that representing this is better in `double` and updated the function in v1.1.

```c
void get_pi(double *pi)
{
    *pi = 3.141592653589793238;
}
```
We run into a big problem. `double` is 8 bytes instead of 4, and the compiler doesn't reserve enough space because it simply doesn't know that it would suddenly change.

You overwrite the return address and crash the program (or worse, you *don't* crash :trollface:).
![ABI stack size bug.png](https://user-images.githubusercontent.com/6258309/166192960-6f0d05cd-59cc-4a71-854a-4e85f91e5387.png)

Similar problems occur when simply reordering struct fields. You write x to offset 4, but the abi expects it to be at offset 12, you write the wrong value.

**Comment by Cyan4973** [comment]
> Do you envision that software might be linked with `xxhash.so` and then shipped to a system with a different (older or newer) `xxhash.so`?

Yes. And this is not just theoretical. Already bitten in production by such cases.

**Comment by iboB** [comment]
OK. Thanks for the info
