### ISSUE TITLE
Some Windows builds (via Julia's Yggdrasil) failing to export functions

### ISSUE THREAD

**Issue by BioTurboNick** [Cyan4973/xxHash#715]
In the code for adding Windows-specific `__declspec(dllimport)` or `__declspec(dllexport)` directives, there is a check for both `WIN32` and `_MSC_VER` being defined, but it should be for all WIN32 builds I believe?

It was changed in commit 701423eeda62b151a437444290a2669f46324f13, but unclear why from the comment.

The underlying issue is that Julia has a binary wrapper system for importing C libraries (https://github.com/JuliaPackaging/Yggdrasil/blob/1c3436bee6347f631af43a3e3bcf5e4dfad6baae/X/xxHash/build_tarballs.jl), and it works on linux but the Windows version fails due to missing imports.

`_MSC_VER` is not defined in the build environment being used.

**Comment by BioTurboNick** [comment]
Or it might be several issues; unclear. XXH_INLINE_ALL might also be defined, which also skips the declarations?

**Comment by Cyan4973** [comment]
When employing `XXH_INLINE_ALL`, it essentially means "do **not** link to the library: inline the code directly instead". 
In which case `XXH_PUBLIC_API` is no longer used to declare which symbols to expose, but rather to keep all the code private (`static`). And therefore, `__declspec(xxxx)` should no longer be reached.

It is important to understand which scenario is being played to diagnose the issue.

**Comment by Cyan4973** [comment]
Looking at : https://github.com/JuliaPackaging/Yggdrasil/blob/1c3436bee6347f631af43a3e3bcf5e4dfad6baae/X/xxHash/build_tarballs.jl#L21

Could you try removing `CPPFLAGS=-DXXH_INLINE_ALL` ?

Compiling the library with this macro setting does not seem like a good idea to me. And it matches well with the symptom that no library symbol is exposed.

**Comment by BioTurboNick** [comment]
Removed `CPPFLAGS=-DXXH_INLINE_ALL`, but that wasn't enough unfortunately.

**Comment by BioTurboNick** [comment]
I tried stripping all the if blocks so that `__declspec(dllexport)` is always present - still produces a DLL without exports.

MSYS2 Windows build works fine. Julia's doesn't.

Is there anything else you could think of to check?

**Comment by Cyan4973** [comment]
No idea. This is way beyond my comfort zone.
I don't even understand what the script is doing.
For example, it's totally unclear to me which compiler is being used

**Comment by BioTurboNick** [comment]
Understandable

Maybe this will help. It's a link to the log output from that script executing: https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=19829&view=logs&j=f7d1000b-fab5-536a-f1b2-2d78b67bde87&t=8ec3aa1b-308e-5c96-731c-f06ecc8d7d6d

Just in case anything stands out. I'll try to keep poking at it with the Julia people.

**Comment by t-mat** [comment]
Frankly, I have no idea too.  But I summarize some part of the log.  Hope this helps.

[Their build platform](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=19829&view=logs&j=96c13d9d-dfd2-51e5-2f76-4a0b3ce09abc&t=09532434-8b0a-5f0e-118d-a3181cde5ec8&l=17) :

```
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
```

[Their PR](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=19829&view=logs&j=896e9295-73d6-533f-41cd-4496539b55c6&t=d7b33a85-883a-57f4-0200-b856ae51fd07&l=41) :

```
...
From https://github.com/JuliaPackaging/Yggdrasil
 + ffd4ca04...477f0b86 refs/pull/4941/merge -> pull/4941/merge  (forced update)
git checkout --progress --force refs/remotes/pull/4941/merge
...
```


## build xxHash-i686-linux-gnu

[Their target](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=19829&view=logs&j=896e9295-73d6-533f-41cd-4496539b55c6&t=09f2e5a5-fab1-5d0d-9c12-b272a1905287&l=14), [compiler and toolchain](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=19829&view=logs&j=896e9295-73d6-533f-41cd-4496539b55c6&t=09f2e5a5-fab1-5d0d-9c12-b272a1905287&l=127)

```
[ Info: Building for i686-linux-gnu
...
[00:43:03] -- The C compiler identification is GNU 4.8.5
/opt/bin/i686-linux-gnu-libgfortran3-cxx03/i686-linux-gnu-gcc
```

[The first error](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=19829&view=logs&j=896e9295-73d6-533f-41cd-4496539b55c6&t=09f2e5a5-fab1-5d0d-9c12-b272a1905287&l=152)
```
[00:43:03] In file included from /workspace/srcdir/xxHash/xxhash.h:320:0,
[00:43:03]                  from /workspace/srcdir/xxHash/xxhash.c:43:
[00:43:03] /opt/i686-linux-gnu/lib/gcc/i686-linux-gnu/4.8.5/include/stddef.h: In function ‘__declspec’:
[00:43:03] /opt/i686-linux-gnu/lib/gcc/i686-linux-gnu/4.8.5/include/stddef.h:147:26: error: storage class specified for parameter ‘ptrdiff_t’
[00:43:03]  typedef __PTRDIFF_TYPE__ ptrdiff_t;
[00:43:03]                           ^
```

As for `i686-linux-gnu`, `__declspec(...)` should be removed.  Because `i686-linux-gnu-gcc` doesn't support it.


## build xxHash-x86_64-w64-mingw32

[Their compiler](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=19829&view=logs&j=f7d1000b-fab5-536a-f1b2-2d78b67bde87&t=8ec3aa1b-308e-5c96-731c-f06ecc8d7d6d&l=149)

```
/opt/bin/x86_64-w64-mingw32-libgfortran3-cxx03/x86_64-w64-mingw32-gcc ...
```

`__declspec(...)` works fine with `x86_64-w64-mingw32-gcc`.  Because `mingw*-gcc` supports `__declspec()` with the following *special* treatment:

https://sourceforge.net/projects/mingw/files/MinGW/Base/gcc/Version4/gcc-4.6.2-1/

```
* Unless the -fno-keep-inline-dllexport compiler flag is given, inline
  functions decorated with __declspec(dllexport) are always generated
  and included in object files. This also applies to methods defined in
  classes decorated with __declspec(dllexport).
```

**Comment by BioTurboNick** [comment]
Thanks @t-mat , but FWIW, that build log for linux is expected to have errors; I was forcing use of `__declspec` to avoid issues with conditional compilation constants not being defined right. So only the Windows one is at issue.

**Comment by t-mat** [comment]
I don't understand your issue yet.  Sorry.

As you know, we can use mingw toolchain to make WIN32 DLL in typical Linux environment with the following standard commands:

```
# setup gcc-mingw-w64
sudo apt-get install gcc-mingw-w64

# clone
cd
git clone --branch v0.8.1 https://github.com/Cyan4973/xxHash.git xxHash-issue-715
cd xxHash-issue-715
git log -1

# Compile
x86_64-w64-mingw32-gcc -O3 -shared xxhash.c -o test-xxhash.dll -Wl,--out-implib,test-libxxhash.lib

# Show exported (public) symbols in the DLL
objdump -p test-xxhash.dll | less -Np XX
```

In this procedure, we don't need any patch for xxHash.[ch].

So I think we should check

(1) Our CMakeLists.txt.
(2) Your build script.
(3) Your build environment.

**Comment by BioTurboNick** [comment]
*Massive facepalm*

The original author of the build script for some reason had a command that grabbed the import library `libxxhash.dll.a` run through the linker again and overwrote `libxxhash.dll`.

Thank you for helping out.
