### ISSUE TITLE
XXH3_kSecret gets duplicated for every translation unit

### ISSUE THREAD

**Issue by dango-msft** [Cyan4973/xxHash#722]
We noticed on a project that due to `XXH3_kSecret` being static, it gets duplicated for every translation unit that includes `xxhash.h`. We end up utilizing it enough that the `XXH3_kSecret` data accounts for roughly ~400KB of duplicated data in our final binary on MSVC. There are multiple ways to go about that problem (especially architecturally on our side), but I want to call out that marking it extern as a declaration and shifting the actual definition of the data to the C file did show us significant impact on binary size. Submitting for consideration whether this is something you'd want to consider.

**Comment by Cyan4973** [comment]
In the "normal" model, `xxhash.o` is a single unit created from `xxhash.c` and hosting `XXH3_kSecret` once.

For above scenario to happen, I assume that `xxhash` is inlined from multiple places in the code base ?

**Comment by DoumanAsh** [comment]
Since it is msvc it is probably C++ which, I believe, will result in `XXH3_kSecret` to fall under internal linkage category
Which means any include of `xxhash.h` would result in copy of static variable within translation unit

I think it should not be the case for C, but I'm not sure (although I think in C `static` simply enforces internal linkage)

P.s. Enabling `lto` should mitigate this issue or including it only in single source file

**Comment by dango-msft** [comment]
Correct to @DoumanAsh 's point, this is a C++ project and we do see a copy of XXH3_kSecret across each translation unit. Happy to do the right tweaks on our side but wanted to point this out in case it was an unintended result. Feel free to close here if "do the right thing" in our codebase is enough

**Comment by dango-msft** [comment]
Closing issue as we were able to work around this with our own wrapper around this
