### ISSUE TITLE
errors from cppcheck

### ISSUE THREAD

**Issue by hzhuang1** [Cyan4973/xxHash#747]
cli/xxhsum.c:62:28: style: union member 'Anonymous0::u' is never used. [unusedStructMember]
    const union { XSUM_U32 u; XSUM_U8 c[4]; } one = { 1 };   /* don't use static: performance detrimental  */
                           ^
tests/bench/benchfn.c:171:33: style: struct member 'tfs_align::c' is never used. [unusedStructMember]
    typedef struct { check_size c; BMK_timedFnState_t tfs; } tfs_align;  /* force tfs to be aligned at its next best position */
                                ^
Could I remove these unused struct member to avoid errors in cppcheck?

**Comment by Cyan4973** [comment]
```
style: union member 'Anonymous0::u' is never used. [unusedStructMember]
const union { XSUM_U32 u; XSUM_U8 c[4]; } one = { 1 }; 
```

That's a pretty weird diagnosis.
The initialization of `one`, present on the very same line, uses the `u` field, right there.
So, that looks to me an incorrect interpretation of the code's behavior, followed by false positive diagnosis.

Unfortunately, that's the pb with static analyzers. They tend to have too many false positives for their signal to be trusted completely. 
As a consequence, they should rather be interpreted as mere hints that maybe something is worth having a look at, but then, one has to use its better judgment to decide if the warning has merits or not.

**Comment by Cyan4973** [comment]
```
style: struct member 'tfs_align::c' is never used. [unusedStructMember]
typedef struct { check_size c; BMK_timedFnState_t tfs; } tfs_align; 
```

The reason for `c` to exist is clearer on the next line of code : 
```
size_t const tfs_alignment = offsetof(tfs_align, tfs); /* provides the minimal alignment restriction for BMK_timedFnState_t */
```

i.e. the only reason for `c` to exist is get the alignment of `BMK_timedFnState_t`.
If the code was `C11`, one could have used `alignof()` instead,
but since this code is trying to remain `C90` compatible,
deriving this information from `alignof` is the next best (portable) thing (excluding compiler's extensions).

This is more difficult to interpret by a static analyzer, hence it's not too surprising that `cppcheck` is not able to make sense of the existence of this variable.
That doesn't make the warning relevant though. Removing `c` would mess up alignment checks, and trigger an exception due to a `% 0` operation later in the code base.
