### ISSUE TITLE
Does xxHash32 really pass SMHasher?

### ISSUE THREAD

**Issue by Bulat-Ziganshin** [Cyan4973/xxHash#77]
Can you please provide your SMHasher tests? Since in my attempt xxHash32 failed the "Differential Tests": https://github.com/Bulat-Ziganshin/FARSH/blob/master/SMHasher/reports/smhasher-XXH32-report.txt#L81

I tried xxHash 0.6.1 with integration code as simple as https://github.com/Bulat-Ziganshin/FARSH/blob/master/SMHasher/xxHashTest.cpp#L4

**Comment by Cyan4973** [comment]
If I do remember correctly,
this test was discovered much later, after xxh32 conception,
and it doesn't pass.

For some reasons, the test wasn't active during xxh32 development.
Maybe because it belonged to the category of "long" tests which were not active by default.

This was fixed for xxh64 development.
But at this stage, xxh32 specification was already frozen.

**Comment by Bulat-Ziganshin** [comment]
Thank you, so i can look into making an improved version.
