### ISSUE TITLE
Scalar xxh3

### ISSUE THREAD

**Issue by aspsk** [Cyan4973/xxHash#793]
Hello! Thanks for your great code!

I have a question about the scalar version of xxh3. (I am interested in the scalar version in order to use it in Linux kernel where we can't use any vectors.) For keys>240 the scalar implementation of `xxh3` starts to be twice slower (and, e.g., is slower than `xxh64`):
```
hash_size 16 32 48 64 80 96 112 128 144 160 176 192 208 224 240 256 272 288 304 320 336 352 368 384 400
xxh3      17 25 33 33 42 42  47  47  68  73  78  83  88  93  98 184 218 218 218 218 252 252 252 252 286
xxh64     26 41 49 48 57 55  63  62  71  70  79  77  86  85  93  92 107 101 110 107 117 118 135 125 134
```
Is this possible to optimize the >240 scalar case or there is some obvious obstacle which prevents this?

**Comment by Cyan4973** [comment]
The "long" mode of `xxh3` (for inputs > 240 bytes) was primarily designed with `SSE2` in mind, with the view that it was a relatively low bar for vector capabilities, and therefore should prove portable on other systems with different kind of vector operations.

While this part proved correct, unfortunately, when removing _any_ kind of vector capability completely out of the picture, it makes the algorithm less optimal. This is what happens with the `SCALAR` mode.

In spite of that, `SCALAR` generally features acceptable performance, though your exact mileage will vary, primarily depending on cpu type and input length.

For example, on my local laptop using a `M1` cpus, for an input of 256 bytes length,
`xxh3_scalar` gets 12.5 GB/s,
while `xxh64` gets 13.5 GB/s.
(for comparison `xxh3_neon` gets 24 GB/s - of course, `M1` supports `NEON`).

So `xxh3_scalar` loses to `xxh64` at 256 bytes input length, though not too badly. And the situation quickly reverses: by 512 bytes, `xxh64` is still running at 13.5 GB/s, while `xxh3_scalar` improves to ~15.5 GB/s .

Of course, this is just a data point using `M1` and local compiler (Apple `clang`), and you seem to experience a very different outcome on your cpu. It could be due to architecture differences, or compiler version, or compilation flags. Difficult to say.

The only thing I'm able to state at this point is that `xxh3_scalar` _can_ provide decent performance compared to `xxh64`, even in the length range where it's unfavorable, but unfortunately the specifics depend on local platform and conditions.

_edit_ : 
I made the same test on an old _skylake_ desktop, and the difference is more substantial.
At 256 bytes : `xxh64` 9.6 GB/s vs  7.6 GB/s `xxh3_scalar`
Furthermore, it doesn't close the distance as easily : 
At 512 bytes : `xxh64` 11.6 GB/s vs 9.6 GB/s `xxh3_scalar`
At 1 KB : `xxh64` 12.2 GB/s vs 11.0 GB/s `xxh3_scalar`

So the difference is more substantial than in the `M1` example, but still not as bad as the reported x2 performance difference of the initial report.

It comes to show that indeed, specific results depend on specific architecture.

_edit 2_ : 
Same test, but _icelake_ laptop, and the ranking is reverse:
At 256 bytes : `xxh64` 6.2 GB/s vs  6.8 GB/s `xxh3_scalar`

**Comment by aspsk** [comment]
Thanks a lot for the numbers! Could you tell me, please, which benchmark did you use? (This one https://github.com/Cyan4973/xxHash/tree/dev/tests/bench ?)

I've tested with gcc and `-O2` (as kernel is built with `-O2`), I will try a newer gcc and clang (and also `-O3`).

**Comment by aspsk** [comment]
Ok, so with `O3` I am seeing better results for `xxh3` (xxh64 doesn't seem to have big diff between O2 and O3):
```
hash_size 16 32 48 64 80 96 112 128 144 160 176 192 208 224 240 256 272 288
xxh3-O2   17 24 32 32 41 41  46  46  67  72  77  82  87  92  97 183 217 217
xxh3-O3   10 24 31 31 41 41  49  49  53  58  63  68  73  78  83 137 158 158
xxh64     25 40 48 47 56 54  63  62  75  69  91  85  86 106 108  93 102 100
```
(gcc 11.3.0, AMD Ryzen 9 running at 3500MHz)

**Comment by Cyan4973** [comment]
Indeed, `xxh32` and `xxh64` were both optimized with `-O2`, so `-O3` doesn't give them much benefit.

But the situation is different with `xxh3`. I presume that several optimizations of vector code, and optimizations of the scalar pipeline to compete with vector code, are currently categorized `-O3` by compilers. This may change over time, but we have little control or visibility over this process.

**Comment by easyaspi314** [comment]
For GCC x86_64 perhaps try
```
-DXXH_VECTOR=0 -mgeneral-regs-only -mno-red-zone -O2 -funroll-loops
```

~~It seems that GCC on -O2 refuses to unroll, but on -O3 constant propagates the entirety of `XXH3_kSecret`, which might not be ideal.~~
Edit: it only does that for the scramble codepath

I may look into some scalar codepath optimizations, as kernel code is a good point and there are some aarch64 codegen issues I am interested in working out.

**Comment by easyaspi314** [comment]
Additionally I want to improve the output of -O2 and -Os/-Oz because a lot of automated build systems default to that.
