### ISSUE TITLE
Support (dummy) command-line options `--text`, `--binary`, etc, for `md5sum` API parity

### ISSUE THREAD

**Issue by MestreLion** [Cyan4973/xxHash#812]
This would allow `xxhsum` to be a drop-in replacement for `md5sum`, the same way `md5sum` also shares its command-line API with the `sha{1,192,256,512}sum` family. Not having to special-case `xxhsum` would tremendously help integrating it in existing scripts.

Such options would obviously be dummy, as xxHash only operates in binary mode. It's debatable whether `--binary`, if explicitly specified, should add the `*` marker or if it should be a true no-op option for compatibility's sake.

As with my previous issue, I'd be willing to provide a PR if this feature is approved

**Comment by t-mat** [comment]
Hi @MestreLion ,
Thanks for your opinion.

In short, I personally support to introduce `--binary`.  But not sure for other proposals.
And please note that `xxhsum` is not a drop-in replacement for `md5sum`.

## "Supporting" `--text`, `-t` but ignore them : :-1: (strongly)

If `xxhsum` accept but ignore `--text`, I think it becomes a trap for users in non-POSIX environment.

Since `xxhsum` doesn't support text mode, I think if `xxhsum` *supports* `--text`, `xxhsum` must report it as an error.

## Supporting `--binary` : :+1:

:+1: for `--binary`.

## Supporting `-b`

I'm not sure for `-b`. Because it has been reserved as a benchmark command since the beginnig of this project.

## `*` as a custom marker

As you know, `xxhsum` just ignore custom markers, I suppose `*` may introduce confusion.  So I think we don't need `*` as a marker.

**Comment by Cyan4973** [comment]
Fully agree with @t-mat well-detailed statements

**Comment by MestreLion** [comment]
Summing it up:
- `--binary`, completely no-op, no `*` in output
- No `-b` as it clashes with current `-b`enchmark (btw, how about a `--benchmark` long option alias?)
- What about `-t|--text`? Unsupported, ok, but _how_? Options:
    - Keep current behavior: error for non-recognized argument
    - Recognize argument but exit with custom error (such as `xxhsum only operates in binary mode`)
    - Same as above, but only when [conditions that would trigger actual text mode](https://unix.stackexchange.com/a/652095/4919) apply.
    - Same as above, but emit warning instead of fatal error (subject to `--status`, `--quiet`, etc)

**Comment by t-mat** [comment]
> Keep current behavior: error for non-recognized argument

If `xxhsum` doesn't accept `--text`, it should behave in same manner.

**Comment by Cyan4973** [comment]
Should we proceed adding support for `--binary` command to `xxhsum` ?

**Comment by t-mat** [comment]
I :+1: for `--binary`.  Even we don't support all (and symmetry) options, it's better than nothing.

**Comment by Cyan4973** [comment]
A few more commands are now supported, thanks to @t-mat 's work on `xxhsum`, though not all. 

Earlier post by @t-mat explains why we can't support them all. Should we close this ticket, or is there something else worth tracking here ?

**Comment by t-mat** [comment]
I think we can close this issue for now.  

We should revisit some related issue before `v1.0` though.

- Reconsider `-b`
- Hack [`digest.c`](https://github.com/coreutils/coreutils/blob/v9.3/src/digest.c) for better compatibility.
  - But it also means less compatibility with Windows, etc.
