### ISSUE TITLE
how do i use xxh3 with perl? there's no module for it. any workarounds?

### ISSUE THREAD

**Issue by kolinfluence** [Cyan4973/xxHash#842]
how do i use xxh3 with perl? there's no module for it. any simple workarounds?

**Comment by t-mat** [comment]
Our list has two Perl xxHash modules but both of them don't support xxh3 as you know.  
https://github.com/Cyan4973/xxHash/blob/94cc7c7f1ecdecbb1ded9cdff7345d1629bcbe44/index.html#L151-L152

So we have no idea at all unfortunately.
Since we don't maintain any Perl module, please ask it in the perl community.
