### ISSUE TITLE
Large code size

### ISSUE THREAD

**Issue by psvz** [Cyan4973/xxHash#844]
If I #include xxhash.h in my .c file and compile, I'll get linker error XXH32() symbol not found. If I then put xxhash.c file in (which only defines static linking) it will increase my .so from 30kB to 330kB in size. I suspect something is wrong here - XXH32 can't be this large, can it?

**Comment by psvz** [comment]
A bit more context: I compile .so and compilation is fine in both cases. But then loading that .so will fail with symbol XXH32 not found. My Makefile:

```
TARGET          = libsawsome.so
CC                  = gcc
CFLAGS          = -g -O2 -Wall -pthread -fpic -shared
LIBS                =

HEADERS         = $(wildcard *.h)
SOURCES         = $(wildcard *.c)
IHEADER         = $(patsubst %.so,%.h,$(TARGET))

$(TARGET): $(HEADERS) $(SOURCES)
        $(CC) $(CFLAGS) -o $@ $^ $(LIBS)

```

**Comment by Cyan4973** [comment]
1) The issue with `XXH32` symbol not found is not normal.
No idea what happened, this seems to be a local issue.
For example, maybe the library is compiled in C++ mode (instead of C), resulting in compile-defined symbol name mangling.

2) The increase in binary size seems excessive.

As a first step, if you are only interested in `XXH32()`, you could disable all other variants.
This can be done by setting `XXH_NO_LONG_LONG`, which will essentially disable everything except `XXH32`.

**Comment by psvz** [comment]
Hi @Cyan4973 - shared my Makefile above. Otherwise it is all standard ubuntu. It might be `-shared` option specifically that triggers something unexpected? Either way, I indeed only need XXH32(). Where do I need to set `XXH_NO_LONG_LONG` and what value? Furthermore, if I'll need XXH64() in the future what should I use to disable everything else? Thanks for your quick answer by the way...

And also, note symbol not found problem is solved by injecting xxhash.c into the compilation. This latter case leads to extra 300kB in size.

Also, I think your advice leads to further complication:
```
gcc -g -O2 -Wall -fpic -shared -dXXH_NO_LONG_LONG -o libarrow.so libarrow.h xxhash.h libarrow.c strlcpy.c xxhash.c
cc1: warning: unrecognized gcc debugging option: X
cc1: warning: unrecognized gcc debugging option: X
cc1: warning: unrecognized gcc debugging option: _
cc1: warning: unrecognized gcc debugging option: O
cc1: warning: unrecognized gcc debugging option: _
cc1: warning: unrecognized gcc debugging option: L
cc1: warning: unrecognized gcc debugging option: O
cc1: warning: unrecognized gcc debugging option: G
cc1: warning: unrecognized gcc debugging option: _
cc1: warning: unrecognized gcc debugging option: L
cc1: warning: unrecognized gcc debugging option: O
cc1: warning: unrecognized gcc debugging option: G
cc1: warning: unrecognized gcc debugging option: X
cc1: warning: unrecognized gcc debugging option: X
cc1: warning: unrecognized gcc debugging option: _
cc1: warning: unrecognized gcc debugging option: O
```

**Comment by t-mat** [comment]
> gcc -g -O2 -Wall -fpic -shared -dXXH_NO_LONG_LONG -o libarrow.so libarrow.h xxhash.h libarrow.c strlcpy.c xxhash.c

`-d` should be spelled `-D`.

```
 v
-dXXH_NO_LONG_LONG # wrong
-DXXH_NO_LONG_LONG # correct
 ^
```

----

Suppose we have the following source code named `my-program.c`.

```C
// my-program.c
#include <string.h>
#include <stdio.h>
#include <xxhash.h>

int main(int argc, char* argv[]) {
    const char* const  str   = "xxHash - Extremely fast hash algorithm";
    size_t const       len   = strlen(str);
    XXH32_hash_t const seed  = 0;
    XXH32_hash_t const xxh32 = XXH32(str, len, 0);

    printf("str = [%s]\n", str);
    printf("seed = 0x%08x\n", seed);
    printf("xxh32 = 0x%08x\n", xxh32);

    return 0;
}
```


## Shared (dynamic) library

If you're trying to use shared (dynamic) library version of xxhash, you have to specify shared library name.  For example, add linker option `-lxxhash`.

```sh
# Dynamic
sudo apt install xxhash libxxhash-dev
cc my-program.c -o xxh-dynamic -lxxhash
./xxh-dynamic
readelf -d ./xxh-dynamic
ls -l ./xxh-dynamic
```


## Static library

If you're trying to use static library version of xxhash, you have to specify static library.  For example, add linker option `-l:libxxhash.a`.

```sh
# Static
sudo apt install xxhash libxxhash-dev
cc my-program.c -o xxh-static -l:libxxhash.a
./xxh-static
readelf -d ./xxh-static
ls -l ./xxh-static
```


## Single-header

If you're trying to use xxhash as a source code form (aka xxhash as a single header library), typically you need to define `XXH_STATIC_LINKING_ONLY` and `XXH_IMPLEMENTATION` before `#include <xxhash.h>`.  
But note that you must make sure your `XXH_IMPLEMENTATION` is defined only once in entire your program.  Otherwise, you'll see "multiple definition" errors.

```sh
# Single-header (not recommended)
sudo apt install xxhash libxxhash-dev
cc my-program.c -o xxh-single -DXXH_STATIC_LINKING_ONLY -DXXH_IMPLEMENTATION
./xxh-single
readelf -d ./xxh-single
ls -l ./xxh-single
```

**Comment by Cyan4973** [comment]
Thanks @t-mat for providing such detailed tutorial.

I think that's the best that can be done here.
