### ISSUE TITLE
[QUESTION] what is the reason behind rotating in `XXH3_len_4to8_64b` case.

### ISSUE THREAD

**Issue by goldsteinn** [Cyan4973/xxHash#854]
Specifically wondering about the following codes:
```
xxh_u32 const input1 = XXH_readLE32(input);
xxh_u32 const input2 = XXH_readLE32(input + len - 4);
xxh_u64 const bitflip = (XXH_readLE64(secret+8) ^ XXH_readLE64(secret+16)) - seed;
xxh_u64 const input64 = input2 + (((xxh_u64)input1) << 32);
```

Is there any particular reason `input2 + (input1 << 32)` is preferable to `input1 + (input2) << 32)`?
Just wondering because if, from a hash quality perspective, its all the same, the latter would generally be preferable.

**Comment by Cyan4973** [comment]
I think this is targeted at the following scenario : 
- `input` is a 64-bit little endian value, representing a coordinate X
- `seed` is a 64-bit integer value, representing a coordinate Y
- X and Y are values expressed roughly within the same range
- we want to ensure that H(X,Y) != H(Y,X)

This kind of scenario may happen in some "Perlin Noise" constructions.
Sure, it's not the only way, nor even the recommended way, to create Perlin Noise. But it just needs to happen in real scenarios from time to time to be a case worth supporting.

That being said, `input2 + (input1 << 32)` is not the only way to support this scenario. I probably settled with this solution due to time pressure, and would probably attempt something different nowadays. `input1 + (input2 << 32)` would indeed be preferable for 64-bit inputs specifically.

**Comment by goldsteinn** [comment]
> I think this is targeted at the following scenario :
> 
> * `input` is a 64-bit little endian value, representing a coordinate X
> * `seed` is a 64-bit integer value, representing a coordinate Y
> * X and Y are values expressed roughly within the same range
> * we want to ensure that H(X,Y) != H(Y,X)
> 
Err yes, with those assumptions :)

> This kind of scenario may happen in some "Perlin Noise" constructions. Sure, it's not the only way, nor even the recommended way, to create Perlin Noise. But it just needs to happen in real scenarios from time to time to be a case worth supporting.
> 
> That being said, `input2 + (input1 << 32)` is not the only way to support this scenario. I probably settled with this solution due to time pressure, and would probably attempt something different nowadays. `input1 + (input2 << 32)` would indeed be preferable for 64-bit inputs specifically.

What would be the preferred solution (not really seeing a list of ways to address this scenario).
