### ISSUE TITLE
release a new version

### ISSUE THREAD

**Issue by celestinoxp** [Cyan4973/xxHash#862]
![image](https://github.com/Cyan4973/xxHash/assets/41735311/5d76024b-c0c8-43fe-b9b4-24d6e625b00b)

Latest release is from 29.Nov.2021 ?

i asked python-xxhash to update to a newer version, then it says it needs xxhash to release a new version... (https://github.com/ifduyue/python-xxhash/issues/63)

We need you to release your new version please thank you

**Comment by t-mat** [comment]
There's no ETA of the next release.  But as @ifduyue mentioned, we're in the landing process of `v0.8.2`.

- https://github.com/Cyan4973/xxHash/commit/0d0e823b385c16f9b6eaa6fb661ef0e5ba6cf316

You can also confirm some ongoing objectives

- https://github.com/Cyan4973/xxHash/issues/458

Please let us know if you have any ideas which should be addressed in the next or future releases.

**Comment by Cyan4973** [comment]
While preparing release `v0.8.2`, I noticed that the performance of `xxh3` for "medium" input sizes has tanked considerably.

Presumably, a prior contribution has been focusing on these input sizes and made things worse instead of better.

I'll bisect and fix, at the cost some time.

As importantly, I wonder how to avoid being blind to such scenarios in the future. We have a very good CI test base to control correctness, but not to control performance evolutions, which could silently become worse has an accidental consequence of a contribution.

**Comment by t-mat** [comment]
I think there're some possible solutions

(1) Buy/rent dedicated machine for nightly benchmarking.
(2) Cycle accurate benchmarking via QEMU + CI.
(3) Benchmark script for local development.  For example, `benchmark.py <oldest-commit-hash> <newest-commit-hash>` checkouts every single commit and build -> benchmark ->report them.

**Comment by Cyan4973** [comment]
Follow up :
only `XXH3_64bits()` is affected.
Among the possible configurations, `x64` is much more impacted than `aarch64`,
the test where the loss is largest is  "throughput random size inputs [1-N]",
and `gcc-9` is much more affected than `clang-12`.

In the worst case scenario, performance is reduced by a factor x3. In less detrimental scenarios, it's still reduced, though by a lesser factor, like -20%.

So this gives a target to look for.

**Comment by easyaspi314** [comment]
> Among the possible configurations, `x64` is much more impacted than `aarch64`

This likely indicates that it is during the finalization because on aarch64 the 64-bit to 128-bit multiplies are the bottleneck, so a bug there would tank performance.

**Comment by easyaspi314** [comment]
Dispatcher/hashLong refactor is 90% done but I need to set up tests and get benchmarks after I get some rest.

Basically, this unifies the dispatching with the outlining of the hashLong code. This requires rewriting of both. 

1. Code size is significantly decreased with minimal overhead by being more clever in how we break up hashLong. There are now only two instances (one with XXH_SIZE_OPT), one for default secret size and one for any secret size. 
2. The dispatcher is more tightly coupled into the logic allowing a more optimal cutoff (which is exactly where we cut off hashLong). As a matter of fact, non-dispatching builds just use a constant folded dispatch table.
3. The dispatcher has some more corner case checks that are for now opt-in
  - Detection of legacy operating systems without SSE2 like Win95 (disabled cuz it's slow and super niche)
  - AVX512 support on macOS (disabled because it's only theoretically correct, I don't have a the hardware)
4. The dispatcher is enabled by default. The code size benefits are literally enough to fit the dispatcher in a negligible if not negative size change from a previous SSE2 binary, and due to the splitting it is just one extra global variable load and an unlikely branch to dispatch.
5. xxhsum now prints XXH_VECTOR with a not set in stone API to retrieve the vector implementation as a string.

There is some room to break it up more but I want the dispatcher to be stable and everything is going to have to be moved anyways.

**Comment by easyaspi314** [comment]
I am having a bit of trouble with the small input latency increase which is about 12% compared to the old dispatcher (on a Ryzen 5 3600 taking AVX2).  

However, I am wondering how much of a tradeoff is worth being able to fit the dispatcher in normal builds without an 80 kB library. Dispatching itself is a latency tradeoff already so idk.

**Comment by Cyan4973** [comment]
It's indeed part of a trade-off.

I can't tell if it's worth it or not with only these elements. It could be, if the binary size saving is very significant.

It looks to me that evaluating this patch will be better done without an urgent timeline constraint, giving time to discuss and ponder different choices when there are, and at least offer a chance of a decent code review, since it will probably be a non-trivial patch.

Therefore, it's probably better to release `v0.8.2` without further delay.
We'll have time then to integrate your binary size optimization patch properly, making it a flagship feature of `v0.8.3`.

**Comment by easyaspi314** [comment]
Agreed. Let's stop waiting on 0.8.2 and push what we have (as long as bugs are fixed) 

I think that the primary goal for next release still should be a stable dispatcher.

**Comment by Cyan4973** [comment]
Release completed
