### ISSUE TITLE
xxh64sum: Argument list too long.

### ISSUE THREAD

**Issue by chellasundar** [Cyan4973/xxHash#87]
Hi Yann,

Good Evening.

Hope all is well.

I try to run the script using xxh32sum and xx64sum file.Its show some error message.

-bash: /root/xxHash-master/xxh64sum: Argument list too long.

Our total file is 29000 Nos.

How many numbers of files can support xxh32sum and xxh64sum script.

Any alternate opensource or paid software is available to check the checksum with sub folder and files.

Thanks,
Chellasundar SR

**Comment by Cyan4973** [comment]
I suspect the problem is that the list of files is so large that it ends up being too large for the shell command buffer, which is typically limited to 2 MB in modern Linux distributions.

I'm afraid there is no solution yet for this problem within `xxhsum`.
You will have to provide the list of files in smaller batches.

`zstd` solves this issue by providing a "recursive" mode, doing the expansion internally, instead of relying on shell. In which case, it's no longer limited by shell command maximum size. 
I guess a future development could be to adapt this mode to `xxhsum`.

**Comment by t-mat** [comment]
Hi, please use `find` and/or `xargs`:
http://askubuntu.com/questions/318530/

You can find many similar solutions by googling with "md5sum recursive".
