### ISSUE TITLE
Collision question

### ISSUE THREAD

**Issue by Noremos** [Cyan4973/xxHash#921]
Hello! Thanks for the library! And sorry for the stupid question.
I need to calculate a hash very quickly, but the problem is that my data is divided into 3 parts: 1 byte and 2 strings.
I tried to use the stream functions, but it is significantly slower than a single function. So I came up with the (probably stupid) idea: use the first hash as a seed for the second hash calculation.

```
auto hash = XXH3_64bits_withSeed(s0.data(), s0.length(), mySecretByte); // Also pass the byte as a seed.
hash = XXH3_64bits_withSeed(s1.data(), s1.length(), hash);
```
So how dangerous is that? Maybe there's a better idea?
I thought about using a secret, but that approach would break if there was a future need to include a different string in the hash calculation (and it's a little slower in terms of performance).

**Comment by Cyan4973** [comment]
This can work.
It depends on how important is collision in your application.

Theoretically, this chaining is a little worse, because a collision on any segment creates a collision for the entire 3-parts set.

Now, a good news is, `XXH3_64bits()` is injective for inputs of `length < 8`, and bijective for `length==8`. Meaning, for any input of length <= 8, there is no collision. So the situation only becomes a bit more risky for segments which are larger than 8 bytes.

So essentially, the first byte as a seed is fine.
And then, for each word of `len > 8`, there is a 1/2^64 chance of collision within one other (different) input.
Assuming all words have a `len > 8` (worst case), the collision rate just doubled.

That's still not much.
Many applications can certainly survive with that.

It depends on:
- how many elements are in the set
- what's the criticity of a collision event

**Comment by Noremos** [comment]
Thank you for the answer. In my case, the first string is about 20 bytes, and the second one is about 100. This isn't the ideal scenario, but the 2^63 chance doesn't seem so scary. Since collisions are not critical in my case, I will try to move forward with my idea. Thanks again.
