### ISSUE TITLE
Any idea how to get xxhash working on a windows CI/CD?

### ISSUE THREAD

**Issue by mofosyne** [Cyan4973/xxHash#955]
In this PR I was getting

> D:\a\llama.cpp\llama.cpp\examples\gguf-hash\deps\xxhash\xxhash.h(1691,1): fatal error C1083: Cannot open include file: 'stdalign.h': No such file or directory [D:\a\llama.cpp\llama.cpp\build\examples\gguf-hash\xxhash.vcxproj]

But can't seem to figure out a solution for it. Attempted this [workaround](https://github.com/ggerganov/llama.cpp/pull/8048/commits/ddfe234ccc03afbf86beb0a33101f9d47c7967c2) but that didn't solve the problem.

https://github.com/ggerganov/llama.cpp/pull/8048

**Comment by t-mat** [comment]
Hi @mofosyne ,

Our CI script has test for cmake + Visual Studio 2019/2022 with plain Windows VM.  It may help you:

https://github.com/Cyan4973/xxHash/blob/805c00b68fa754200ada0c207ffeaa7a4409377c/.github/workflows/ci.yml#L508-L578

Also, there're similar (but resolved) questions:

- https://github.com/Cyan4973/xxHash/issues/487
- https://github.com/Cyan4973/xxHash/issues/666

**Comment by mofosyne** [comment]
Thanks for the pointers.

If it would help, this approach seems to be working if you want to add some changes to work around this issue for others.

```c
/* Windows SDK under 10.0.22000 is missing stdalign.h so we add a check
   before allowing the windows compiler to use the C11 form.
   Reference: https://github.com/Cyan4973/xxHash/issues/955 */
#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L) \
    && (defined(_MSC_VER) && (_MSC_VER >= 1000) || !defined(_MSC_VER)) /* >= C11 */
#  include <stdalign.h>
#  define XXH_ALIGN(n)      alignas(n)
#elif defined(__cplusplus) && (__cplusplus >= 201103L) /* >= C++11 */
/* In C++ alignas() is a keyword */
#  define XXH_ALIGN(n)      alignas(n)
#elif defined(__GNUC__)
#  define XXH_ALIGN(n)      __attribute__ ((aligned(n)))
#elif defined(_MSC_VER)
#  define XXH_ALIGN(n)      __declspec(align(n))
#else
#  define XXH_ALIGN(n)   /* disabled */
#endif
```

**Comment by t-mat** [comment]
> ```C
> #if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L) \
>     && (defined(_MSC_VER) && (_MSC_VER >= 1000) || !defined(_MSC_VER)) /* >= C11 */
> ```

It seems `_MSC_VER >= 1000` doesn't work as expected since VC++6.0's (MSVC 1998) `_MSC_VER` is `1200`.

So, let me guessing the nicest `_MSC_VER` which supports "stdalign.h" properly.

- The first Windows SDK which contains "stdalign.h" is [Windows SDK 10.0.20348.0](https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/) (a.k.a. "version 2104")
- We can say that the following and later version of Visual Studio / MSVC has shipped with "proper" version of Windows SDK.
  - Visual Studio 2019 version 16.11 has been released [Apr, 2021](https://learn.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.11.0)
    - `_MSC_VER` is `1929`
  - Visual Studio 2022 version 17.1.4 has been released [Apr, 2021](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.1#17.1.4)
    - `_MSC_VER` is `1931`

Therefore, 

- The most widely compatible version of `_MSC_VER` may be `1929`
- The most safely compatible version of `_MSC_VER` may be `1932`

@mofosyne , could you try these versions in your environment ?

----

See also : `_MSC_VER` table in [Microsoft Visual C++ compiler versioning](https://learn.microsoft.com/en-us/cpp/overview/compiler-versions?view=msvc-170#version-macros)

**Comment by mofosyne** [comment]
Don't have access to a Microsoft compiler, it was for the llama.cpp GitHub actions in the PR mentioned above. So can't help you too much there. Basically did some guess work to at least make it compile.

But I get that you need to be more accurate to make a suitable PR to solve this issue. Unfortunately I won't be able to help there.

**Comment by Cyan4973** [comment]
Looking around, we can find multiple examples of projects failing to compile on Visual Studio 2019 due to lack of `<stdalign.h>` header.

Apparently, Visual Studio only supports `C11` fully [since VS2019 `v16.8`](https://devblogs.microsoft.com/visualstudio/visual-studio-2019-v16-8/).

Prior versions seem to have "partial support", meaning they might claim compliance with `C11`, yet not fully deliver, and in particular not provide `<stdalign.h>`, even though it's in the mandatory part of the specification (which is not a correct behavior, the compiler should not claim compliance if it's not fully compliant).

That would make `_MSC_VER` **1928** the minimum version number to check.

I'm surprised the proposed check `(_MSC_VER >= 1000)` has proven helpful.
According to Microsoft documentation, the smallest value of `_MSC_VER` seems to be `1200`, meaning any version of Visual Studio would advertise a value larger than 1000.

Finally, another work around could be to use `_Alignas()` instead, since it is a language keyword, as opposed to a macro defined within an `#include` header. That would skip the need to include `<stdalign.h>`.
